In [1]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine
load_dotenv(override=True)
url = os.getenv("MYSQL_URL")

In [2]:
import db_utils
import importlib

importlib.reload(db_utils)

<module 'db_utils' from 'c:\\Users\\Dell\\Data_Engineering_Workspace\\db_utils.py'>

In [3]:
df = pd.read_csv("Superstore_utf8.csv")
df.shape

(9994, 21)

In [5]:
db_utils.run_mysql_query("""
SHOW CREATE TABLE superstore.staging_sales;
""")

'Execution successful. Rows affected: 1'

In [6]:
db_utils.run_mysql_query("""
SELECT 
    TABLE_NAME,
    TABLE_ROWS
FROM information_schema.tables
WHERE TABLE_SCHEMA = 'superstore'
AND TABLE_NAME = 'staging_sales';
""")

,TABLE_NAME,TABLE_ROWS
0,staging_sales,0


In [7]:
db_utils.run_mysql_query("""
SELECT 
    COLUMN_NAME,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_KEY
FROM information_schema.columns
WHERE TABLE_SCHEMA = 'superstore'
AND TABLE_NAME = 'staging_sales'
ORDER BY ORDINAL_POSITION;
""")

,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_KEY
0,row_id,int,NO,PRI
1,order_id,varchar(20),YES,
2,order_date,date,YES,
3,ship_date,date,YES,
4,ship_mode,varchar(20),YES,
5,customer_id,varchar(20),YES,
6,customer_name,varchar(100),YES,
7,segment,varchar(50),YES,
8,country,varchar(100),YES,
9,city,varchar(100),YES,


In [8]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [9]:
staging_df = df.rename(columns={
    "Row ID": "row_id",
    "Order ID": "order_id",
    "Order Date": "order_date",
    "Ship Date": "ship_date",
    "Ship Mode": "ship_mode",
    "Customer ID": "customer_id",
    "Customer Name": "customer_name",
    "Segment": "segment",
    "Country": "country",
    "City": "city",
    "State": "state",
    "Postal Code": "postal_code",
    "Region": "region",
    "Product ID": "product_id",
    "Category": "category",
    "Sub-Category": "sub_category",
    "Product Name": "product_name",
    "Sales": "sales",
    "Quantity": "quantity",
    "Discount": "discount",
    "Profit": "profit"
})

In [10]:
staging_df["order_date"] = pd.to_datetime(staging_df["order_date"])
staging_df["ship_date"] = pd.to_datetime(staging_df["ship_date"])

In [11]:
staging_df.shape

(9994, 21)

In [12]:
staging_df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164


In [13]:
import os
from sqlalchemy import create_engine
load_dotenv(override=True)

mysql_url = os.getenv("MYSQL_URL")

engine = create_engine(
    mysql_url,
    pool_pre_ping=True
)
with engine.connect() as conn:
    print("MySQL connection successful!")

MySQL connection successful!


In [15]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT DATABASE()"))
    print(result.fetchone())

('defaultdb',)


In [16]:
from sqlalchemy import create_engine
from sqlalchemy.engine import make_url

url = make_url(mysql_url)

superstore_url = url.set(database="superstore")

engine_superstore = create_engine(
    superstore_url,
    pool_pre_ping=True
)

In [17]:
with engine_superstore.connect() as conn:
    result = conn.execute(text("SELECT DATABASE()"))
    print(result.fetchone())

('superstore',)


In [18]:
staging_df.to_sql(
    "staging_sales",
    con=engine_superstore,
    if_exists="append",
    index=False,
    chunksize=1000,
    method="multi"
)

9994

In [19]:
db_utils.run_mysql_query("""
SELECT COUNT(*) AS row_count
FROM superstore.staging_sales;
""")

,row_count
0,9994


In [20]:
db_utils.run_mysql_query("""
SELECT 
    COUNT(*) AS total_rows,
    COUNT(DISTINCT row_id) AS unique_row_ids
FROM superstore.staging_sales;
""")

,total_rows,unique_row_ids
0,9994,9994


In [21]:
db_utils.run_mysql_query("""
SELECT
    COUNT(*) AS total_rows,
    SUM(row_id IS NULL) AS null_row_id,
    SUM(order_id IS NULL) AS null_order_id,
    SUM(customer_id IS NULL) AS null_customer_id,
    SUM(product_id IS NULL) AS null_product_id,
    SUM(sales IS NULL) AS null_sales,
    SUM(quantity IS NULL) AS null_quantity,
    SUM(profit IS NULL) AS null_profit
FROM superstore.staging_sales;
""")

,total_rows,null_row_id,null_order_id,null_customer_id,null_product_id,null_sales,null_quantity,null_profit
0,9994,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [22]:
!git pull origin main

remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 19 (delta 7), reused 19 (delta 7), pack-reused 0 (from 0)
Unpacking objects: 100% (19/19), 5.67 MiB | 15.00 KiB/s, done.
From https://github.com/leodera/Data_Engineering_Workspace
 * branch            main       -> FETCH_HEAD
   431eded..3e4a73e  main       -> origin/main
Updating 431eded..3e4a73e
error: Your local changes to the following files would be overwritten by merge:
	Untitled1.ipynb
	nano_02_rfm_quantiles.ipynb
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
	.ipynb_checkpoints/data_cleaning-checkpoint.ipynb
	.ipynb_checkpoints/db_utils-checkpoint.py
	.ipynb_checkpoints/nano_02_rfm_quantiles-checkpoint.ipynb
	data_cleaning.ipynb
	db_utils.py
Please move or remove them before you merge.
Aborting


In [20]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv(override=True)

mysql_engine = create_engine(
    os.getenv("MYSQL_URL"),
    pool_pre_ping=True
)

postgres_engine = create_engine(
    os.getenv("POSTGRES_URL"),
    pool_pre_ping=True
)

In [24]:
with mysql_engine.connect() as conn:
    print("MySQL:", conn.execute(text("SELECT DATABASE()")).scalar())

with postgres_engine.connect() as conn:
    print("PostgreSQL:", conn.execute(text("SELECT current_database()")).scalar())

MySQL: defaultdb
PostgreSQL: defaultdb


In [25]:
from sqlalchemy.engine import make_url

url = make_url(os.getenv("MYSQL_URL"))

superstore_mysql_url = url.set(database="superstore")

mysql_engine = create_engine(
    superstore_mysql_url,
    pool_pre_ping=True
)

In [26]:
with mysql_engine.connect() as conn:
    print(
        "MySQL database:",
        conn.execute(text("SELECT DATABASE()")).scalar()
    )

MySQL database: superstore


In [27]:
db_utils.run_pg_query("""
CREATE SCHEMA IF NOT EXISTS superstore;
""")

'Execution successful. Rows affected: -1'

In [28]:
db_utils.run_pg_query("""
SELECT schema_name
FROM information_schema.schemata
WHERE schema_name = 'superstore';
""")

,schema_name
0,superstore


In [29]:
db_utils.run_pg_query("""
CREATE TABLE IF NOT EXISTS superstore.customers (
    customer_id VARCHAR(20) PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    segment VARCHAR(50),
    country VARCHAR(100)
);
""")

db_utils.run_pg_query("""
CREATE TABLE IF NOT EXISTS superstore.products (
    product_key INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(20) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    sub_category VARCHAR(100) NOT NULL
);
""")

db_utils.run_pg_query("""
CREATE TABLE IF NOT EXISTS superstore.orders (
    order_id VARCHAR(20) PRIMARY KEY,
    customer_id VARCHAR(20) NOT NULL,
    order_date DATE NOT NULL,
    ship_date DATE NOT NULL,
    ship_mode VARCHAR(20) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(10) NOT NULL,
    region VARCHAR(20) NOT NULL,

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES superstore.customers(customer_id)
);
""")

db_utils.run_pg_query("""
CREATE TABLE IF NOT EXISTS superstore.order_items (
    row_id INTEGER PRIMARY KEY,
    order_id VARCHAR(20) NOT NULL,
    product_key INTEGER NOT NULL,
    sales NUMERIC(15,4) NOT NULL,
    quantity INTEGER NOT NULL,
    discount NUMERIC(5,4) NOT NULL,
    profit NUMERIC(15,4) NOT NULL,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES superstore.orders(order_id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_key)
        REFERENCES superstore.products(product_key)
);
""")

'Execution successful. Rows affected: -1'

In [32]:
db_utils.run_pg_query("""
SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'superstore'
ORDER BY table_name;
""")

,table_schema,table_name
0,superstore,customers
1,superstore,order_items
2,superstore,orders
3,superstore,products
4,superstore,sample_superstore
5,superstore,v_super


In [36]:
from sqlalchemy.engine import make_url

mysql_url = make_url(os.getenv("MYSQL_URL"))
mysql_superstore_url = mysql_url.set(database="superstore")

mysql_engine = create_engine(
    mysql_superstore_url,
    pool_pre_ping=True
)

with mysql_engine.connect() as conn:
    print(conn.execute(text("SELECT DATABASE()")).scalar())

customers_df = pd.read_sql(
    "SELECT * FROM Customers",
    mysql_engine
)

products_df = pd.read_sql(
    "SELECT * FROM Products",
    mysql_engine
)

orders_df = pd.read_sql(
    "SELECT * FROM Orders",
    mysql_engine
)

order_items_df = pd.read_sql(
    "SELECT * FROM Order_Items",
    mysql_engine
)

customers_df.to_sql(
    "customers",
    con=postgres_engine,
    schema="superstore",
    if_exists="append",
    index=False,
    chunksize=1000,
    method="multi"
)

superstore


793

In [39]:
products_df[["product_key", "product_id", "product_name"]].head() 

print("Customers:", customers_df.shape)
print("Products:", products_df.shape)
print("Orders:", orders_df.shape)
print("Order Items:", order_items_df.shape)

Customers: (793, 4)
Products: (1894, 5)
Orders: (5009, 9)
Order Items: (9994, 7)


In [40]:
products_df.to_sql(
    "products",
    con=postgres_engine,
    schema="superstore",
    if_exists="append",
    index=False,
    chunksize=1000,
    method="multi"
)

ProgrammingError: (psycopg2.errors.GeneratedAlways) cannot insert a non-DEFAULT value into column "product_key"
DETAIL:  Column "product_key" is an identity column defined as GENERATED ALWAYS.
HINT:  Use OVERRIDING SYSTEM VALUE to override.

[SQL: INSERT INTO superstore.products (product_key, product_id, product_name, category, sub_category) VALUES (%(product_key_m0)s, %(product_id_m0)s, %(product_name_m0)s, %(category_m0)s, %(sub_category_m0)s), (%(product_key_m1)s, %(product_id_m1)s, %(product_name_m1)s, %(category_m1)s, %(sub_category_m1)s), (%(product_key_m2)s, %(product_id_m2)s, %(product_name_m2)s, %(category_m2)s, %(sub_category_m2)s), (%(product_key_m3)s, %(product_id_m3)s, %(product_name_m3)s, %(category_m3)s, %(sub_category_m3)s), (%(product_key_m4)s, %(product_id_m4)s, %(product_name_m4)s, %(category_m4)s, %(sub_category_m4)s), (%(product_key_m5)s, %(product_id_m5)s, %(product_name_m5)s, %(category_m5)s, %(sub_category_m5)s), (%(product_key_m6)s, %(product_id_m6)s, %(product_name_m6)s, %(category_m6)s, %(sub_category_m6)s), (%(product_key_m7)s, %(product_id_m7)s, %(product_name_m7)s, %(category_m7)s, %(sub_category_m7)s), (%(product_key_m8)s, %(product_id_m8)s, %(product_name_m8)s, %(category_m8)s, %(sub_category_m8)s), (%(product_key_m9)s, %(product_id_m9)s, %(product_name_m9)s, %(category_m9)s, %(sub_category_m9)s), (%(product_key_m10)s, %(product_id_m10)s, %(product_name_m10)s, %(category_m10)s, %(sub_category_m10)s), (%(product_key_m11)s, %(product_id_m11)s, %(product_name_m11)s, %(category_m11)s, %(sub_category_m11)s), (%(product_key_m12)s, %(product_id_m12)s, %(product_name_m12)s, %(category_m12)s, %(sub_category_m12)s), (%(product_key_m13)s, %(product_id_m13)s, %(product_name_m13)s, %(category_m13)s, %(sub_category_m13)s), (%(product_key_m14)s, %(product_id_m14)s, %(product_name_m14)s, %(category_m14)s, %(sub_category_m14)s), (%(product_key_m15)s, %(product_id_m15)s, %(product_name_m15)s, %(category_m15)s, %(sub_category_m15)s), (%(product_key_m16)s, %(product_id_m16)s, %(product_name_m16)s, %(category_m16)s, %(sub_category_m16)s), (%(product_key_m17)s, %(product_id_m17)s, %(product_name_m17)s, %(category_m17)s, %(sub_category_m17)s), (%(product_key_m18)s, %(product_id_m18)s, %(product_name_m18)s, %(category_m18)s, %(sub_category_m18)s), (%(product_key_m19)s, %(product_id_m19)s, %(product_name_m19)s, %(category_m19)s, %(sub_category_m19)s), (%(product_key_m20)s, %(product_id_m20)s, %(product_name_m20)s, %(category_m20)s, %(sub_category_m20)s), (%(product_key_m21)s, %(product_id_m21)s, %(product_name_m21)s, %(category_m21)s, %(sub_category_m21)s), (%(product_key_m22)s, %(product_id_m22)s, %(product_name_m22)s, %(category_m22)s, %(sub_category_m22)s), (%(product_key_m23)s, %(product_id_m23)s, %(product_name_m23)s, %(category_m23)s, %(sub_category_m23)s), (%(product_key_m24)s, %(product_id_m24)s, %(product_name_m24)s, %(category_m24)s, %(sub_category_m24)s), (%(product_key_m25)s, %(product_id_m25)s, %(product_name_m25)s, %(category_m25)s, %(sub_category_m25)s), (%(product_key_m26)s, %(product_id_m26)s, %(product_name_m26)s, %(category_m26)s, %(sub_category_m26)s), (%(product_key_m27)s, %(product_id_m27)s, %(product_name_m27)s, %(category_m27)s, %(sub_category_m27)s), (%(product_key_m28)s, %(product_id_m28)s, %(product_name_m28)s, %(category_m28)s, %(sub_category_m28)s), (%(product_key_m29)s, %(product_id_m29)s, %(product_name_m29)s, %(category_m29)s, %(sub_category_m29)s), (%(product_key_m30)s, %(product_id_m30)s, %(product_name_m30)s, %(category_m30)s, %(sub_category_m30)s), (%(product_key_m31)s, %(product_id_m31)s, %(product_name_m31)s, %(category_m31)s, %(sub_category_m31)s), (%(product_key_m32)s, %(product_id_m32)s, %(product_name_m32)s, %(category_m32)s, %(sub_category_m32)s), (%(product_key_m33)s, %(product_id_m33)s, %(product_name_m33)s, %(category_m33)s, %(sub_category_m33)s), (%(product_key_m34)s, %(product_id_m34)s, %(product_name_m34)s, %(category_m34)s, %(sub_category_m34)s), (%(product_key_m35)s, %(product_id_m35)s, %(product_name_m35)s, %(category_m35)s, %(sub_category_m35)s), (%(product_key_m36)s, %(product_id_m36)s, %(product_name_m36)s, %(category_m36)s, %(sub_category_m36)s), (%(product_key_m37)s, %(product_id_m37)s, %(product_name_m37)s, %(category_m37)s, %(sub_category_m37)s), (%(product_key_m38)s, %(product_id_m38)s, %(product_name_m38)s, %(category_m38)s, %(sub_category_m38)s), (%(product_key_m39)s, %(product_id_m39)s, %(product_name_m39)s, %(category_m39)s, %(sub_category_m39)s), (%(product_key_m40)s, %(product_id_m40)s, %(product_name_m40)s, %(category_m40)s, %(sub_category_m40)s), (%(product_key_m41)s, %(product_id_m41)s, %(product_name_m41)s, %(category_m41)s, %(sub_category_m41)s), (%(product_key_m42)s, %(product_id_m42)s, %(product_name_m42)s, %(category_m42)s, %(sub_category_m42)s), (%(product_key_m43)s, %(product_id_m43)s, %(product_name_m43)s, %(category_m43)s, %(sub_category_m43)s), (%(product_key_m44)s, %(product_id_m44)s, %(product_name_m44)s, %(category_m44)s, %(sub_category_m44)s), (%(product_key_m45)s, %(product_id_m45)s, %(product_name_m45)s, %(category_m45)s, %(sub_category_m45)s), (%(product_key_m46)s, %(product_id_m46)s, %(product_name_m46)s, %(category_m46)s, %(sub_category_m46)s), (%(product_key_m47)s, %(product_id_m47)s, %(product_name_m47)s, %(category_m47)s, %(sub_category_m47)s), (%(product_key_m48)s, %(product_id_m48)s, %(product_name_m48)s, %(category_m48)s, %(sub_category_m48)s), (%(product_key_m49)s, %(product_id_m49)s, %(product_name_m49)s, %(category_m49)s, %(sub_category_m49)s), (%(product_key_m50)s, %(product_id_m50)s, %(product_name_m50)s, %(category_m50)s, %(sub_category_m50)s), (%(product_key_m51)s, %(product_id_m51)s, %(product_name_m51)s, %(category_m51)s, %(sub_category_m51)s), (%(product_key_m52)s, %(product_id_m52)s, %(product_name_m52)s, %(category_m52)s, %(sub_category_m52)s), (%(product_key_m53)s, %(product_id_m53)s, %(product_name_m53)s, %(category_m53)s, %(sub_category_m53)s), (%(product_key_m54)s, %(product_id_m54)s, %(product_name_m54)s, %(category_m54)s, %(sub_category_m54)s), (%(product_key_m55)s, %(product_id_m55)s, %(product_name_m55)s, %(category_m55)s, %(sub_category_m55)s), (%(product_key_m56)s, %(product_id_m56)s, %(product_name_m56)s, %(category_m56)s, %(sub_category_m56)s), (%(product_key_m57)s, %(product_id_m57)s, %(product_name_m57)s, %(category_m57)s, %(sub_category_m57)s), (%(product_key_m58)s, %(product_id_m58)s, %(product_name_m58)s, %(category_m58)s, %(sub_category_m58)s), (%(product_key_m59)s, %(product_id_m59)s, %(product_name_m59)s, %(category_m59)s, %(sub_category_m59)s), (%(product_key_m60)s, %(product_id_m60)s, %(product_name_m60)s, %(category_m60)s, %(sub_category_m60)s), (%(product_key_m61)s, %(product_id_m61)s, %(product_name_m61)s, %(category_m61)s, %(sub_category_m61)s), (%(product_key_m62)s, %(product_id_m62)s, %(product_name_m62)s, %(category_m62)s, %(sub_category_m62)s), (%(product_key_m63)s, %(product_id_m63)s, %(product_name_m63)s, %(category_m63)s, %(sub_category_m63)s), (%(product_key_m64)s, %(product_id_m64)s, %(product_name_m64)s, %(category_m64)s, %(sub_category_m64)s), (%(product_key_m65)s, %(product_id_m65)s, %(product_name_m65)s, %(category_m65)s, %(sub_category_m65)s), (%(product_key_m66)s, %(product_id_m66)s, %(product_name_m66)s, %(category_m66)s, %(sub_category_m66)s), (%(product_key_m67)s, %(product_id_m67)s, %(product_name_m67)s, %(category_m67)s, %(sub_category_m67)s), (%(product_key_m68)s, %(product_id_m68)s, %(product_name_m68)s, %(category_m68)s, %(sub_category_m68)s), (%(product_key_m69)s, %(product_id_m69)s, %(product_name_m69)s, %(category_m69)s, %(sub_category_m69)s), (%(product_key_m70)s, %(product_id_m70)s, %(product_name_m70)s, %(category_m70)s, %(sub_category_m70)s), (%(product_key_m71)s, %(product_id_m71)s, %(product_name_m71)s, %(category_m71)s, %(sub_category_m71)s), (%(product_key_m72)s, %(product_id_m72)s, %(product_name_m72)s, %(category_m72)s, %(sub_category_m72)s), (%(product_key_m73)s, %(product_id_m73)s, %(product_name_m73)s, %(category_m73)s, %(sub_category_m73)s), (%(product_key_m74)s, %(product_id_m74)s, %(product_name_m74)s, %(category_m74)s, %(sub_category_m74)s), (%(product_key_m75)s, %(product_id_m75)s, %(product_name_m75)s, %(category_m75)s, %(sub_category_m75)s), (%(product_key_m76)s, %(product_id_m76)s, %(product_name_m76)s, %(category_m76)s, %(sub_category_m76)s), (%(product_key_m77)s, %(product_id_m77)s, %(product_name_m77)s, %(category_m77)s, %(sub_category_m77)s), (%(product_key_m78)s, %(product_id_m78)s, %(product_name_m78)s, %(category_m78)s, %(sub_category_m78)s), (%(product_key_m79)s, %(product_id_m79)s, %(product_name_m79)s, %(category_m79)s, %(sub_category_m79)s), (%(product_key_m80)s, %(product_id_m80)s, %(product_name_m80)s, %(category_m80)s, %(sub_category_m80)s), (%(product_key_m81)s, %(product_id_m81)s, %(product_name_m81)s, %(category_m81)s, %(sub_category_m81)s), (%(product_key_m82)s, %(product_id_m82)s, %(product_name_m82)s, %(category_m82)s, %(sub_category_m82)s), (%(product_key_m83)s, %(product_id_m83)s, %(product_name_m83)s, %(category_m83)s, %(sub_category_m83)s), (%(product_key_m84)s, %(product_id_m84)s, %(product_name_m84)s, %(category_m84)s, %(sub_category_m84)s), (%(product_key_m85)s, %(product_id_m85)s, %(product_name_m85)s, %(category_m85)s, %(sub_category_m85)s), (%(product_key_m86)s, %(product_id_m86)s, %(product_name_m86)s, %(category_m86)s, %(sub_category_m86)s), (%(product_key_m87)s, %(product_id_m87)s, %(product_name_m87)s, %(category_m87)s, %(sub_category_m87)s), (%(product_key_m88)s, %(product_id_m88)s, %(product_name_m88)s, %(category_m88)s, %(sub_category_m88)s), (%(product_key_m89)s, %(product_id_m89)s, %(product_name_m89)s, %(category_m89)s, %(sub_category_m89)s), (%(product_key_m90)s, %(product_id_m90)s, %(product_name_m90)s, %(category_m90)s, %(sub_category_m90)s), (%(product_key_m91)s, %(product_id_m91)s, %(product_name_m91)s, %(category_m91)s, %(sub_category_m91)s), (%(product_key_m92)s, %(product_id_m92)s, %(product_name_m92)s, %(category_m92)s, %(sub_category_m92)s), (%(product_key_m93)s, %(product_id_m93)s, %(product_name_m93)s, %(category_m93)s, %(sub_category_m93)s), (%(product_key_m94)s, %(product_id_m94)s, %(product_name_m94)s, %(category_m94)s, %(sub_category_m94)s), (%(product_key_m95)s, %(product_id_m95)s, %(product_name_m95)s, %(category_m95)s, %(sub_category_m95)s), (%(product_key_m96)s, %(product_id_m96)s, %(product_name_m96)s, %(category_m96)s, %(sub_category_m96)s), (%(product_key_m97)s, %(product_id_m97)s, %(product_name_m97)s, %(category_m97)s, %(sub_category_m97)s), (%(product_key_m98)s, %(product_id_m98)s, %(product_name_m98)s, %(category_m98)s, %(sub_category_m98)s), (%(product_key_m99)s, %(product_id_m99)s, %(product_name_m99)s, %(category_m99)s, %(sub_category_m99)s), (%(product_key_m100)s, %(product_id_m100)s, %(product_name_m100)s, %(category_m100)s, %(sub_category_m100)s), (%(product_key_m101)s, %(product_id_m101)s, %(product_name_m101)s, %(category_m101)s, %(sub_category_m101)s), (%(product_key_m102)s, %(product_id_m102)s, %(product_name_m102)s, %(category_m102)s, %(sub_category_m102)s), (%(product_key_m103)s, %(product_id_m103)s, %(product_name_m103)s, %(category_m103)s, %(sub_category_m103)s), (%(product_key_m104)s, %(product_id_m104)s, %(product_name_m104)s, %(category_m104)s, %(sub_category_m104)s), (%(product_key_m105)s, %(product_id_m105)s, %(product_name_m105)s, %(category_m105)s, %(sub_category_m105)s), (%(product_key_m106)s, %(product_id_m106)s, %(product_name_m106)s, %(category_m106)s, %(sub_category_m106)s), (%(product_key_m107)s, %(product_id_m107)s, %(product_name_m107)s, %(category_m107)s, %(sub_category_m107)s), (%(product_key_m108)s, %(product_id_m108)s, %(product_name_m108)s, %(category_m108)s, %(sub_category_m108)s), (%(product_key_m109)s, %(product_id_m109)s, %(product_name_m109)s, %(category_m109)s, %(sub_category_m109)s), (%(product_key_m110)s, %(product_id_m110)s, %(product_name_m110)s, %(category_m110)s, %(sub_category_m110)s), (%(product_key_m111)s, %(product_id_m111)s, %(product_name_m111)s, %(category_m111)s, %(sub_category_m111)s), (%(product_key_m112)s, %(product_id_m112)s, %(product_name_m112)s, %(category_m112)s, %(sub_category_m112)s), (%(product_key_m113)s, %(product_id_m113)s, %(product_name_m113)s, %(category_m113)s, %(sub_category_m113)s), (%(product_key_m114)s, %(product_id_m114)s, %(product_name_m114)s, %(category_m114)s, %(sub_category_m114)s), (%(product_key_m115)s, %(product_id_m115)s, %(product_name_m115)s, %(category_m115)s, %(sub_category_m115)s), (%(product_key_m116)s, %(product_id_m116)s, %(product_name_m116)s, %(category_m116)s, %(sub_category_m116)s), (%(product_key_m117)s, %(product_id_m117)s, %(product_name_m117)s, %(category_m117)s, %(sub_category_m117)s), (%(product_key_m118)s, %(product_id_m118)s, %(product_name_m118)s, %(category_m118)s, %(sub_category_m118)s), (%(product_key_m119)s, %(product_id_m119)s, %(product_name_m119)s, %(category_m119)s, %(sub_category_m119)s), (%(product_key_m120)s, %(product_id_m120)s, %(product_name_m120)s, %(category_m120)s, %(sub_category_m120)s), (%(product_key_m121)s, %(product_id_m121)s, %(product_name_m121)s, %(category_m121)s, %(sub_category_m121)s), (%(product_key_m122)s, %(product_id_m122)s, %(product_name_m122)s, %(category_m122)s, %(sub_category_m122)s), (%(product_key_m123)s, %(product_id_m123)s, %(product_name_m123)s, %(category_m123)s, %(sub_category_m123)s), (%(product_key_m124)s, %(product_id_m124)s, %(product_name_m124)s, %(category_m124)s, %(sub_category_m124)s), (%(product_key_m125)s, %(product_id_m125)s, %(product_name_m125)s, %(category_m125)s, %(sub_category_m125)s), (%(product_key_m126)s, %(product_id_m126)s, %(product_name_m126)s, %(category_m126)s, %(sub_category_m126)s), (%(product_key_m127)s, %(product_id_m127)s, %(product_name_m127)s, %(category_m127)s, %(sub_category_m127)s), (%(product_key_m128)s, %(product_id_m128)s, %(product_name_m128)s, %(category_m128)s, %(sub_category_m128)s), (%(product_key_m129)s, %(product_id_m129)s, %(product_name_m129)s, %(category_m129)s, %(sub_category_m129)s), (%(product_key_m130)s, %(product_id_m130)s, %(product_name_m130)s, %(category_m130)s, %(sub_category_m130)s), (%(product_key_m131)s, %(product_id_m131)s, %(product_name_m131)s, %(category_m131)s, %(sub_category_m131)s), (%(product_key_m132)s, %(product_id_m132)s, %(product_name_m132)s, %(category_m132)s, %(sub_category_m132)s), (%(product_key_m133)s, %(product_id_m133)s, %(product_name_m133)s, %(category_m133)s, %(sub_category_m133)s), (%(product_key_m134)s, %(product_id_m134)s, %(product_name_m134)s, %(category_m134)s, %(sub_category_m134)s), (%(product_key_m135)s, %(product_id_m135)s, %(product_name_m135)s, %(category_m135)s, %(sub_category_m135)s), (%(product_key_m136)s, %(product_id_m136)s, %(product_name_m136)s, %(category_m136)s, %(sub_category_m136)s), (%(product_key_m137)s, %(product_id_m137)s, %(product_name_m137)s, %(category_m137)s, %(sub_category_m137)s), (%(product_key_m138)s, %(product_id_m138)s, %(product_name_m138)s, %(category_m138)s, %(sub_category_m138)s), (%(product_key_m139)s, %(product_id_m139)s, %(product_name_m139)s, %(category_m139)s, %(sub_category_m139)s), (%(product_key_m140)s, %(product_id_m140)s, %(product_name_m140)s, %(category_m140)s, %(sub_category_m140)s), (%(product_key_m141)s, %(product_id_m141)s, %(product_name_m141)s, %(category_m141)s, %(sub_category_m141)s), (%(product_key_m142)s, %(product_id_m142)s, %(product_name_m142)s, %(category_m142)s, %(sub_category_m142)s), (%(product_key_m143)s, %(product_id_m143)s, %(product_name_m143)s, %(category_m143)s, %(sub_category_m143)s), (%(product_key_m144)s, %(product_id_m144)s, %(product_name_m144)s, %(category_m144)s, %(sub_category_m144)s), (%(product_key_m145)s, %(product_id_m145)s, %(product_name_m145)s, %(category_m145)s, %(sub_category_m145)s), (%(product_key_m146)s, %(product_id_m146)s, %(product_name_m146)s, %(category_m146)s, %(sub_category_m146)s), (%(product_key_m147)s, %(product_id_m147)s, %(product_name_m147)s, %(category_m147)s, %(sub_category_m147)s), (%(product_key_m148)s, %(product_id_m148)s, %(product_name_m148)s, %(category_m148)s, %(sub_category_m148)s), (%(product_key_m149)s, %(product_id_m149)s, %(product_name_m149)s, %(category_m149)s, %(sub_category_m149)s), (%(product_key_m150)s, %(product_id_m150)s, %(product_name_m150)s, %(category_m150)s, %(sub_category_m150)s), (%(product_key_m151)s, %(product_id_m151)s, %(product_name_m151)s, %(category_m151)s, %(sub_category_m151)s), (%(product_key_m152)s, %(product_id_m152)s, %(product_name_m152)s, %(category_m152)s, %(sub_category_m152)s), (%(product_key_m153)s, %(product_id_m153)s, %(product_name_m153)s, %(category_m153)s, %(sub_category_m153)s), (%(product_key_m154)s, %(product_id_m154)s, %(product_name_m154)s, %(category_m154)s, %(sub_category_m154)s), (%(product_key_m155)s, %(product_id_m155)s, %(product_name_m155)s, %(category_m155)s, %(sub_category_m155)s), (%(product_key_m156)s, %(product_id_m156)s, %(product_name_m156)s, %(category_m156)s, %(sub_category_m156)s), (%(product_key_m157)s, %(product_id_m157)s, %(product_name_m157)s, %(category_m157)s, %(sub_category_m157)s), (%(product_key_m158)s, %(product_id_m158)s, %(product_name_m158)s, %(category_m158)s, %(sub_category_m158)s), (%(product_key_m159)s, %(product_id_m159)s, %(product_name_m159)s, %(category_m159)s, %(sub_category_m159)s), (%(product_key_m160)s, %(product_id_m160)s, %(product_name_m160)s, %(category_m160)s, %(sub_category_m160)s), (%(product_key_m161)s, %(product_id_m161)s, %(product_name_m161)s, %(category_m161)s, %(sub_category_m161)s), (%(product_key_m162)s, %(product_id_m162)s, %(product_name_m162)s, %(category_m162)s, %(sub_category_m162)s), (%(product_key_m163)s, %(product_id_m163)s, %(product_name_m163)s, %(category_m163)s, %(sub_category_m163)s), (%(product_key_m164)s, %(product_id_m164)s, %(product_name_m164)s, %(category_m164)s, %(sub_category_m164)s), (%(product_key_m165)s, %(product_id_m165)s, %(product_name_m165)s, %(category_m165)s, %(sub_category_m165)s), (%(product_key_m166)s, %(product_id_m166)s, %(product_name_m166)s, %(category_m166)s, %(sub_category_m166)s), (%(product_key_m167)s, %(product_id_m167)s, %(product_name_m167)s, %(category_m167)s, %(sub_category_m167)s), (%(product_key_m168)s, %(product_id_m168)s, %(product_name_m168)s, %(category_m168)s, %(sub_category_m168)s), (%(product_key_m169)s, %(product_id_m169)s, %(product_name_m169)s, %(category_m169)s, %(sub_category_m169)s), (%(product_key_m170)s, %(product_id_m170)s, %(product_name_m170)s, %(category_m170)s, %(sub_category_m170)s), (%(product_key_m171)s, %(product_id_m171)s, %(product_name_m171)s, %(category_m171)s, %(sub_category_m171)s), (%(product_key_m172)s, %(product_id_m172)s, %(product_name_m172)s, %(category_m172)s, %(sub_category_m172)s), (%(product_key_m173)s, %(product_id_m173)s, %(product_name_m173)s, %(category_m173)s, %(sub_category_m173)s), (%(product_key_m174)s, %(product_id_m174)s, %(product_name_m174)s, %(category_m174)s, %(sub_category_m174)s), (%(product_key_m175)s, %(product_id_m175)s, %(product_name_m175)s, %(category_m175)s, %(sub_category_m175)s), (%(product_key_m176)s, %(product_id_m176)s, %(product_name_m176)s, %(category_m176)s, %(sub_category_m176)s), (%(product_key_m177)s, %(product_id_m177)s, %(product_name_m177)s, %(category_m177)s, %(sub_category_m177)s), (%(product_key_m178)s, %(product_id_m178)s, %(product_name_m178)s, %(category_m178)s, %(sub_category_m178)s), (%(product_key_m179)s, %(product_id_m179)s, %(product_name_m179)s, %(category_m179)s, %(sub_category_m179)s), (%(product_key_m180)s, %(product_id_m180)s, %(product_name_m180)s, %(category_m180)s, %(sub_category_m180)s), (%(product_key_m181)s, %(product_id_m181)s, %(product_name_m181)s, %(category_m181)s, %(sub_category_m181)s), (%(product_key_m182)s, %(product_id_m182)s, %(product_name_m182)s, %(category_m182)s, %(sub_category_m182)s), (%(product_key_m183)s, %(product_id_m183)s, %(product_name_m183)s, %(category_m183)s, %(sub_category_m183)s), (%(product_key_m184)s, %(product_id_m184)s, %(product_name_m184)s, %(category_m184)s, %(sub_category_m184)s), (%(product_key_m185)s, %(product_id_m185)s, %(product_name_m185)s, %(category_m185)s, %(sub_category_m185)s), (%(product_key_m186)s, %(product_id_m186)s, %(product_name_m186)s, %(category_m186)s, %(sub_category_m186)s), (%(product_key_m187)s, %(product_id_m187)s, %(product_name_m187)s, %(category_m187)s, %(sub_category_m187)s), (%(product_key_m188)s, %(product_id_m188)s, %(product_name_m188)s, %(category_m188)s, %(sub_category_m188)s), (%(product_key_m189)s, %(product_id_m189)s, %(product_name_m189)s, %(category_m189)s, %(sub_category_m189)s), (%(product_key_m190)s, %(product_id_m190)s, %(product_name_m190)s, %(category_m190)s, %(sub_category_m190)s), (%(product_key_m191)s, %(product_id_m191)s, %(product_name_m191)s, %(category_m191)s, %(sub_category_m191)s), (%(product_key_m192)s, %(product_id_m192)s, %(product_name_m192)s, %(category_m192)s, %(sub_category_m192)s), (%(product_key_m193)s, %(product_id_m193)s, %(product_name_m193)s, %(category_m193)s, %(sub_category_m193)s), (%(product_key_m194)s, %(product_id_m194)s, %(product_name_m194)s, %(category_m194)s, %(sub_category_m194)s), (%(product_key_m195)s, %(product_id_m195)s, %(product_name_m195)s, %(category_m195)s, %(sub_category_m195)s), (%(product_key_m196)s, %(product_id_m196)s, %(product_name_m196)s, %(category_m196)s, %(sub_category_m196)s), (%(product_key_m197)s, %(product_id_m197)s, %(product_name_m197)s, %(category_m197)s, %(sub_category_m197)s), (%(product_key_m198)s, %(product_id_m198)s, %(product_name_m198)s, %(category_m198)s, %(sub_category_m198)s), (%(product_key_m199)s, %(product_id_m199)s, %(product_name_m199)s, %(category_m199)s, %(sub_category_m199)s), (%(product_key_m200)s, %(product_id_m200)s, %(product_name_m200)s, %(category_m200)s, %(sub_category_m200)s), (%(product_key_m201)s, %(product_id_m201)s, %(product_name_m201)s, %(category_m201)s, %(sub_category_m201)s), (%(product_key_m202)s, %(product_id_m202)s, %(product_name_m202)s, %(category_m202)s, %(sub_category_m202)s), (%(product_key_m203)s, %(product_id_m203)s, %(product_name_m203)s, %(category_m203)s, %(sub_category_m203)s), (%(product_key_m204)s, %(product_id_m204)s, %(product_name_m204)s, %(category_m204)s, %(sub_category_m204)s), (%(product_key_m205)s, %(product_id_m205)s, %(product_name_m205)s, %(category_m205)s, %(sub_category_m205)s), (%(product_key_m206)s, %(product_id_m206)s, %(product_name_m206)s, %(category_m206)s, %(sub_category_m206)s), (%(product_key_m207)s, %(product_id_m207)s, %(product_name_m207)s, %(category_m207)s, %(sub_category_m207)s), (%(product_key_m208)s, %(product_id_m208)s, %(product_name_m208)s, %(category_m208)s, %(sub_category_m208)s), (%(product_key_m209)s, %(product_id_m209)s, %(product_name_m209)s, %(category_m209)s, %(sub_category_m209)s), (%(product_key_m210)s, %(product_id_m210)s, %(product_name_m210)s, %(category_m210)s, %(sub_category_m210)s), (%(product_key_m211)s, %(product_id_m211)s, %(product_name_m211)s, %(category_m211)s, %(sub_category_m211)s), (%(product_key_m212)s, %(product_id_m212)s, %(product_name_m212)s, %(category_m212)s, %(sub_category_m212)s), (%(product_key_m213)s, %(product_id_m213)s, %(product_name_m213)s, %(category_m213)s, %(sub_category_m213)s), (%(product_key_m214)s, %(product_id_m214)s, %(product_name_m214)s, %(category_m214)s, %(sub_category_m214)s), (%(product_key_m215)s, %(product_id_m215)s, %(product_name_m215)s, %(category_m215)s, %(sub_category_m215)s), (%(product_key_m216)s, %(product_id_m216)s, %(product_name_m216)s, %(category_m216)s, %(sub_category_m216)s), (%(product_key_m217)s, %(product_id_m217)s, %(product_name_m217)s, %(category_m217)s, %(sub_category_m217)s), (%(product_key_m218)s, %(product_id_m218)s, %(product_name_m218)s, %(category_m218)s, %(sub_category_m218)s), (%(product_key_m219)s, %(product_id_m219)s, %(product_name_m219)s, %(category_m219)s, %(sub_category_m219)s), (%(product_key_m220)s, %(product_id_m220)s, %(product_name_m220)s, %(category_m220)s, %(sub_category_m220)s), (%(product_key_m221)s, %(product_id_m221)s, %(product_name_m221)s, %(category_m221)s, %(sub_category_m221)s), (%(product_key_m222)s, %(product_id_m222)s, %(product_name_m222)s, %(category_m222)s, %(sub_category_m222)s), (%(product_key_m223)s, %(product_id_m223)s, %(product_name_m223)s, %(category_m223)s, %(sub_category_m223)s), (%(product_key_m224)s, %(product_id_m224)s, %(product_name_m224)s, %(category_m224)s, %(sub_category_m224)s), (%(product_key_m225)s, %(product_id_m225)s, %(product_name_m225)s, %(category_m225)s, %(sub_category_m225)s), (%(product_key_m226)s, %(product_id_m226)s, %(product_name_m226)s, %(category_m226)s, %(sub_category_m226)s), (%(product_key_m227)s, %(product_id_m227)s, %(product_name_m227)s, %(category_m227)s, %(sub_category_m227)s), (%(product_key_m228)s, %(product_id_m228)s, %(product_name_m228)s, %(category_m228)s, %(sub_category_m228)s), (%(product_key_m229)s, %(product_id_m229)s, %(product_name_m229)s, %(category_m229)s, %(sub_category_m229)s), (%(product_key_m230)s, %(product_id_m230)s, %(product_name_m230)s, %(category_m230)s, %(sub_category_m230)s), (%(product_key_m231)s, %(product_id_m231)s, %(product_name_m231)s, %(category_m231)s, %(sub_category_m231)s), (%(product_key_m232)s, %(product_id_m232)s, %(product_name_m232)s, %(category_m232)s, %(sub_category_m232)s), (%(product_key_m233)s, %(product_id_m233)s, %(product_name_m233)s, %(category_m233)s, %(sub_category_m233)s), (%(product_key_m234)s, %(product_id_m234)s, %(product_name_m234)s, %(category_m234)s, %(sub_category_m234)s), (%(product_key_m235)s, %(product_id_m235)s, %(product_name_m235)s, %(category_m235)s, %(sub_category_m235)s), (%(product_key_m236)s, %(product_id_m236)s, %(product_name_m236)s, %(category_m236)s, %(sub_category_m236)s), (%(product_key_m237)s, %(product_id_m237)s, %(product_name_m237)s, %(category_m237)s, %(sub_category_m237)s), (%(product_key_m238)s, %(product_id_m238)s, %(product_name_m238)s, %(category_m238)s, %(sub_category_m238)s), (%(product_key_m239)s, %(product_id_m239)s, %(product_name_m239)s, %(category_m239)s, %(sub_category_m239)s), (%(product_key_m240)s, %(product_id_m240)s, %(product_name_m240)s, %(category_m240)s, %(sub_category_m240)s), (%(product_key_m241)s, %(product_id_m241)s, %(product_name_m241)s, %(category_m241)s, %(sub_category_m241)s), (%(product_key_m242)s, %(product_id_m242)s, %(product_name_m242)s, %(category_m242)s, %(sub_category_m242)s), (%(product_key_m243)s, %(product_id_m243)s, %(product_name_m243)s, %(category_m243)s, %(sub_category_m243)s), (%(product_key_m244)s, %(product_id_m244)s, %(product_name_m244)s, %(category_m244)s, %(sub_category_m244)s), (%(product_key_m245)s, %(product_id_m245)s, %(product_name_m245)s, %(category_m245)s, %(sub_category_m245)s), (%(product_key_m246)s, %(product_id_m246)s, %(product_name_m246)s, %(category_m246)s, %(sub_category_m246)s), (%(product_key_m247)s, %(product_id_m247)s, %(product_name_m247)s, %(category_m247)s, %(sub_category_m247)s), (%(product_key_m248)s, %(product_id_m248)s, %(product_name_m248)s, %(category_m248)s, %(sub_category_m248)s), (%(product_key_m249)s, %(product_id_m249)s, %(product_name_m249)s, %(category_m249)s, %(sub_category_m249)s), (%(product_key_m250)s, %(product_id_m250)s, %(product_name_m250)s, %(category_m250)s, %(sub_category_m250)s), (%(product_key_m251)s, %(product_id_m251)s, %(product_name_m251)s, %(category_m251)s, %(sub_category_m251)s), (%(product_key_m252)s, %(product_id_m252)s, %(product_name_m252)s, %(category_m252)s, %(sub_category_m252)s), (%(product_key_m253)s, %(product_id_m253)s, %(product_name_m253)s, %(category_m253)s, %(sub_category_m253)s), (%(product_key_m254)s, %(product_id_m254)s, %(product_name_m254)s, %(category_m254)s, %(sub_category_m254)s), (%(product_key_m255)s, %(product_id_m255)s, %(product_name_m255)s, %(category_m255)s, %(sub_category_m255)s), (%(product_key_m256)s, %(product_id_m256)s, %(product_name_m256)s, %(category_m256)s, %(sub_category_m256)s), (%(product_key_m257)s, %(product_id_m257)s, %(product_name_m257)s, %(category_m257)s, %(sub_category_m257)s), (%(product_key_m258)s, %(product_id_m258)s, %(product_name_m258)s, %(category_m258)s, %(sub_category_m258)s), (%(product_key_m259)s, %(product_id_m259)s, %(product_name_m259)s, %(category_m259)s, %(sub_category_m259)s), (%(product_key_m260)s, %(product_id_m260)s, %(product_name_m260)s, %(category_m260)s, %(sub_category_m260)s), (%(product_key_m261)s, %(product_id_m261)s, %(product_name_m261)s, %(category_m261)s, %(sub_category_m261)s), (%(product_key_m262)s, %(product_id_m262)s, %(product_name_m262)s, %(category_m262)s, %(sub_category_m262)s), (%(product_key_m263)s, %(product_id_m263)s, %(product_name_m263)s, %(category_m263)s, %(sub_category_m263)s), (%(product_key_m264)s, %(product_id_m264)s, %(product_name_m264)s, %(category_m264)s, %(sub_category_m264)s), (%(product_key_m265)s, %(product_id_m265)s, %(product_name_m265)s, %(category_m265)s, %(sub_category_m265)s), (%(product_key_m266)s, %(product_id_m266)s, %(product_name_m266)s, %(category_m266)s, %(sub_category_m266)s), (%(product_key_m267)s, %(product_id_m267)s, %(product_name_m267)s, %(category_m267)s, %(sub_category_m267)s), (%(product_key_m268)s, %(product_id_m268)s, %(product_name_m268)s, %(category_m268)s, %(sub_category_m268)s), (%(product_key_m269)s, %(product_id_m269)s, %(product_name_m269)s, %(category_m269)s, %(sub_category_m269)s), (%(product_key_m270)s, %(product_id_m270)s, %(product_name_m270)s, %(category_m270)s, %(sub_category_m270)s), (%(product_key_m271)s, %(product_id_m271)s, %(product_name_m271)s, %(category_m271)s, %(sub_category_m271)s), (%(product_key_m272)s, %(product_id_m272)s, %(product_name_m272)s, %(category_m272)s, %(sub_category_m272)s), (%(product_key_m273)s, %(product_id_m273)s, %(product_name_m273)s, %(category_m273)s, %(sub_category_m273)s), (%(product_key_m274)s, %(product_id_m274)s, %(product_name_m274)s, %(category_m274)s, %(sub_category_m274)s), (%(product_key_m275)s, %(product_id_m275)s, %(product_name_m275)s, %(category_m275)s, %(sub_category_m275)s), (%(product_key_m276)s, %(product_id_m276)s, %(product_name_m276)s, %(category_m276)s, %(sub_category_m276)s), (%(product_key_m277)s, %(product_id_m277)s, %(product_name_m277)s, %(category_m277)s, %(sub_category_m277)s), (%(product_key_m278)s, %(product_id_m278)s, %(product_name_m278)s, %(category_m278)s, %(sub_category_m278)s), (%(product_key_m279)s, %(product_id_m279)s, %(product_name_m279)s, %(category_m279)s, %(sub_category_m279)s), (%(product_key_m280)s, %(product_id_m280)s, %(product_name_m280)s, %(category_m280)s, %(sub_category_m280)s), (%(product_key_m281)s, %(product_id_m281)s, %(product_name_m281)s, %(category_m281)s, %(sub_category_m281)s), (%(product_key_m282)s, %(product_id_m282)s, %(product_name_m282)s, %(category_m282)s, %(sub_category_m282)s), (%(product_key_m283)s, %(product_id_m283)s, %(product_name_m283)s, %(category_m283)s, %(sub_category_m283)s), (%(product_key_m284)s, %(product_id_m284)s, %(product_name_m284)s, %(category_m284)s, %(sub_category_m284)s), (%(product_key_m285)s, %(product_id_m285)s, %(product_name_m285)s, %(category_m285)s, %(sub_category_m285)s), (%(product_key_m286)s, %(product_id_m286)s, %(product_name_m286)s, %(category_m286)s, %(sub_category_m286)s), (%(product_key_m287)s, %(product_id_m287)s, %(product_name_m287)s, %(category_m287)s, %(sub_category_m287)s), (%(product_key_m288)s, %(product_id_m288)s, %(product_name_m288)s, %(category_m288)s, %(sub_category_m288)s), (%(product_key_m289)s, %(product_id_m289)s, %(product_name_m289)s, %(category_m289)s, %(sub_category_m289)s), (%(product_key_m290)s, %(product_id_m290)s, %(product_name_m290)s, %(category_m290)s, %(sub_category_m290)s), (%(product_key_m291)s, %(product_id_m291)s, %(product_name_m291)s, %(category_m291)s, %(sub_category_m291)s), (%(product_key_m292)s, %(product_id_m292)s, %(product_name_m292)s, %(category_m292)s, %(sub_category_m292)s), (%(product_key_m293)s, %(product_id_m293)s, %(product_name_m293)s, %(category_m293)s, %(sub_category_m293)s), (%(product_key_m294)s, %(product_id_m294)s, %(product_name_m294)s, %(category_m294)s, %(sub_category_m294)s), (%(product_key_m295)s, %(product_id_m295)s, %(product_name_m295)s, %(category_m295)s, %(sub_category_m295)s), (%(product_key_m296)s, %(product_id_m296)s, %(product_name_m296)s, %(category_m296)s, %(sub_category_m296)s), (%(product_key_m297)s, %(product_id_m297)s, %(product_name_m297)s, %(category_m297)s, %(sub_category_m297)s), (%(product_key_m298)s, %(product_id_m298)s, %(product_name_m298)s, %(category_m298)s, %(sub_category_m298)s), (%(product_key_m299)s, %(product_id_m299)s, %(product_name_m299)s, %(category_m299)s, %(sub_category_m299)s), (%(product_key_m300)s, %(product_id_m300)s, %(product_name_m300)s, %(category_m300)s, %(sub_category_m300)s), (%(product_key_m301)s, %(product_id_m301)s, %(product_name_m301)s, %(category_m301)s, %(sub_category_m301)s), (%(product_key_m302)s, %(product_id_m302)s, %(product_name_m302)s, %(category_m302)s, %(sub_category_m302)s), (%(product_key_m303)s, %(product_id_m303)s, %(product_name_m303)s, %(category_m303)s, %(sub_category_m303)s), (%(product_key_m304)s, %(product_id_m304)s, %(product_name_m304)s, %(category_m304)s, %(sub_category_m304)s), (%(product_key_m305)s, %(product_id_m305)s, %(product_name_m305)s, %(category_m305)s, %(sub_category_m305)s), (%(product_key_m306)s, %(product_id_m306)s, %(product_name_m306)s, %(category_m306)s, %(sub_category_m306)s), (%(product_key_m307)s, %(product_id_m307)s, %(product_name_m307)s, %(category_m307)s, %(sub_category_m307)s), (%(product_key_m308)s, %(product_id_m308)s, %(product_name_m308)s, %(category_m308)s, %(sub_category_m308)s), (%(product_key_m309)s, %(product_id_m309)s, %(product_name_m309)s, %(category_m309)s, %(sub_category_m309)s), (%(product_key_m310)s, %(product_id_m310)s, %(product_name_m310)s, %(category_m310)s, %(sub_category_m310)s), (%(product_key_m311)s, %(product_id_m311)s, %(product_name_m311)s, %(category_m311)s, %(sub_category_m311)s), (%(product_key_m312)s, %(product_id_m312)s, %(product_name_m312)s, %(category_m312)s, %(sub_category_m312)s), (%(product_key_m313)s, %(product_id_m313)s, %(product_name_m313)s, %(category_m313)s, %(sub_category_m313)s), (%(product_key_m314)s, %(product_id_m314)s, %(product_name_m314)s, %(category_m314)s, %(sub_category_m314)s), (%(product_key_m315)s, %(product_id_m315)s, %(product_name_m315)s, %(category_m315)s, %(sub_category_m315)s), (%(product_key_m316)s, %(product_id_m316)s, %(product_name_m316)s, %(category_m316)s, %(sub_category_m316)s), (%(product_key_m317)s, %(product_id_m317)s, %(product_name_m317)s, %(category_m317)s, %(sub_category_m317)s), (%(product_key_m318)s, %(product_id_m318)s, %(product_name_m318)s, %(category_m318)s, %(sub_category_m318)s), (%(product_key_m319)s, %(product_id_m319)s, %(product_name_m319)s, %(category_m319)s, %(sub_category_m319)s), (%(product_key_m320)s, %(product_id_m320)s, %(product_name_m320)s, %(category_m320)s, %(sub_category_m320)s), (%(product_key_m321)s, %(product_id_m321)s, %(product_name_m321)s, %(category_m321)s, %(sub_category_m321)s), (%(product_key_m322)s, %(product_id_m322)s, %(product_name_m322)s, %(category_m322)s, %(sub_category_m322)s), (%(product_key_m323)s, %(product_id_m323)s, %(product_name_m323)s, %(category_m323)s, %(sub_category_m323)s), (%(product_key_m324)s, %(product_id_m324)s, %(product_name_m324)s, %(category_m324)s, %(sub_category_m324)s), (%(product_key_m325)s, %(product_id_m325)s, %(product_name_m325)s, %(category_m325)s, %(sub_category_m325)s), (%(product_key_m326)s, %(product_id_m326)s, %(product_name_m326)s, %(category_m326)s, %(sub_category_m326)s), (%(product_key_m327)s, %(product_id_m327)s, %(product_name_m327)s, %(category_m327)s, %(sub_category_m327)s), (%(product_key_m328)s, %(product_id_m328)s, %(product_name_m328)s, %(category_m328)s, %(sub_category_m328)s), (%(product_key_m329)s, %(product_id_m329)s, %(product_name_m329)s, %(category_m329)s, %(sub_category_m329)s), (%(product_key_m330)s, %(product_id_m330)s, %(product_name_m330)s, %(category_m330)s, %(sub_category_m330)s), (%(product_key_m331)s, %(product_id_m331)s, %(product_name_m331)s, %(category_m331)s, %(sub_category_m331)s), (%(product_key_m332)s, %(product_id_m332)s, %(product_name_m332)s, %(category_m332)s, %(sub_category_m332)s), (%(product_key_m333)s, %(product_id_m333)s, %(product_name_m333)s, %(category_m333)s, %(sub_category_m333)s), (%(product_key_m334)s, %(product_id_m334)s, %(product_name_m334)s, %(category_m334)s, %(sub_category_m334)s), (%(product_key_m335)s, %(product_id_m335)s, %(product_name_m335)s, %(category_m335)s, %(sub_category_m335)s), (%(product_key_m336)s, %(product_id_m336)s, %(product_name_m336)s, %(category_m336)s, %(sub_category_m336)s), (%(product_key_m337)s, %(product_id_m337)s, %(product_name_m337)s, %(category_m337)s, %(sub_category_m337)s), (%(product_key_m338)s, %(product_id_m338)s, %(product_name_m338)s, %(category_m338)s, %(sub_category_m338)s), (%(product_key_m339)s, %(product_id_m339)s, %(product_name_m339)s, %(category_m339)s, %(sub_category_m339)s), (%(product_key_m340)s, %(product_id_m340)s, %(product_name_m340)s, %(category_m340)s, %(sub_category_m340)s), (%(product_key_m341)s, %(product_id_m341)s, %(product_name_m341)s, %(category_m341)s, %(sub_category_m341)s), (%(product_key_m342)s, %(product_id_m342)s, %(product_name_m342)s, %(category_m342)s, %(sub_category_m342)s), (%(product_key_m343)s, %(product_id_m343)s, %(product_name_m343)s, %(category_m343)s, %(sub_category_m343)s), (%(product_key_m344)s, %(product_id_m344)s, %(product_name_m344)s, %(category_m344)s, %(sub_category_m344)s), (%(product_key_m345)s, %(product_id_m345)s, %(product_name_m345)s, %(category_m345)s, %(sub_category_m345)s), (%(product_key_m346)s, %(product_id_m346)s, %(product_name_m346)s, %(category_m346)s, %(sub_category_m346)s), (%(product_key_m347)s, %(product_id_m347)s, %(product_name_m347)s, %(category_m347)s, %(sub_category_m347)s), (%(product_key_m348)s, %(product_id_m348)s, %(product_name_m348)s, %(category_m348)s, %(sub_category_m348)s), (%(product_key_m349)s, %(product_id_m349)s, %(product_name_m349)s, %(category_m349)s, %(sub_category_m349)s), (%(product_key_m350)s, %(product_id_m350)s, %(product_name_m350)s, %(category_m350)s, %(sub_category_m350)s), (%(product_key_m351)s, %(product_id_m351)s, %(product_name_m351)s, %(category_m351)s, %(sub_category_m351)s), (%(product_key_m352)s, %(product_id_m352)s, %(product_name_m352)s, %(category_m352)s, %(sub_category_m352)s), (%(product_key_m353)s, %(product_id_m353)s, %(product_name_m353)s, %(category_m353)s, %(sub_category_m353)s), (%(product_key_m354)s, %(product_id_m354)s, %(product_name_m354)s, %(category_m354)s, %(sub_category_m354)s), (%(product_key_m355)s, %(product_id_m355)s, %(product_name_m355)s, %(category_m355)s, %(sub_category_m355)s), (%(product_key_m356)s, %(product_id_m356)s, %(product_name_m356)s, %(category_m356)s, %(sub_category_m356)s), (%(product_key_m357)s, %(product_id_m357)s, %(product_name_m357)s, %(category_m357)s, %(sub_category_m357)s), (%(product_key_m358)s, %(product_id_m358)s, %(product_name_m358)s, %(category_m358)s, %(sub_category_m358)s), (%(product_key_m359)s, %(product_id_m359)s, %(product_name_m359)s, %(category_m359)s, %(sub_category_m359)s), (%(product_key_m360)s, %(product_id_m360)s, %(product_name_m360)s, %(category_m360)s, %(sub_category_m360)s), (%(product_key_m361)s, %(product_id_m361)s, %(product_name_m361)s, %(category_m361)s, %(sub_category_m361)s), (%(product_key_m362)s, %(product_id_m362)s, %(product_name_m362)s, %(category_m362)s, %(sub_category_m362)s), (%(product_key_m363)s, %(product_id_m363)s, %(product_name_m363)s, %(category_m363)s, %(sub_category_m363)s), (%(product_key_m364)s, %(product_id_m364)s, %(product_name_m364)s, %(category_m364)s, %(sub_category_m364)s), (%(product_key_m365)s, %(product_id_m365)s, %(product_name_m365)s, %(category_m365)s, %(sub_category_m365)s), (%(product_key_m366)s, %(product_id_m366)s, %(product_name_m366)s, %(category_m366)s, %(sub_category_m366)s), (%(product_key_m367)s, %(product_id_m367)s, %(product_name_m367)s, %(category_m367)s, %(sub_category_m367)s), (%(product_key_m368)s, %(product_id_m368)s, %(product_name_m368)s, %(category_m368)s, %(sub_category_m368)s), (%(product_key_m369)s, %(product_id_m369)s, %(product_name_m369)s, %(category_m369)s, %(sub_category_m369)s), (%(product_key_m370)s, %(product_id_m370)s, %(product_name_m370)s, %(category_m370)s, %(sub_category_m370)s), (%(product_key_m371)s, %(product_id_m371)s, %(product_name_m371)s, %(category_m371)s, %(sub_category_m371)s), (%(product_key_m372)s, %(product_id_m372)s, %(product_name_m372)s, %(category_m372)s, %(sub_category_m372)s), (%(product_key_m373)s, %(product_id_m373)s, %(product_name_m373)s, %(category_m373)s, %(sub_category_m373)s), (%(product_key_m374)s, %(product_id_m374)s, %(product_name_m374)s, %(category_m374)s, %(sub_category_m374)s), (%(product_key_m375)s, %(product_id_m375)s, %(product_name_m375)s, %(category_m375)s, %(sub_category_m375)s), (%(product_key_m376)s, %(product_id_m376)s, %(product_name_m376)s, %(category_m376)s, %(sub_category_m376)s), (%(product_key_m377)s, %(product_id_m377)s, %(product_name_m377)s, %(category_m377)s, %(sub_category_m377)s), (%(product_key_m378)s, %(product_id_m378)s, %(product_name_m378)s, %(category_m378)s, %(sub_category_m378)s), (%(product_key_m379)s, %(product_id_m379)s, %(product_name_m379)s, %(category_m379)s, %(sub_category_m379)s), (%(product_key_m380)s, %(product_id_m380)s, %(product_name_m380)s, %(category_m380)s, %(sub_category_m380)s), (%(product_key_m381)s, %(product_id_m381)s, %(product_name_m381)s, %(category_m381)s, %(sub_category_m381)s), (%(product_key_m382)s, %(product_id_m382)s, %(product_name_m382)s, %(category_m382)s, %(sub_category_m382)s), (%(product_key_m383)s, %(product_id_m383)s, %(product_name_m383)s, %(category_m383)s, %(sub_category_m383)s), (%(product_key_m384)s, %(product_id_m384)s, %(product_name_m384)s, %(category_m384)s, %(sub_category_m384)s), (%(product_key_m385)s, %(product_id_m385)s, %(product_name_m385)s, %(category_m385)s, %(sub_category_m385)s), (%(product_key_m386)s, %(product_id_m386)s, %(product_name_m386)s, %(category_m386)s, %(sub_category_m386)s), (%(product_key_m387)s, %(product_id_m387)s, %(product_name_m387)s, %(category_m387)s, %(sub_category_m387)s), (%(product_key_m388)s, %(product_id_m388)s, %(product_name_m388)s, %(category_m388)s, %(sub_category_m388)s), (%(product_key_m389)s, %(product_id_m389)s, %(product_name_m389)s, %(category_m389)s, %(sub_category_m389)s), (%(product_key_m390)s, %(product_id_m390)s, %(product_name_m390)s, %(category_m390)s, %(sub_category_m390)s), (%(product_key_m391)s, %(product_id_m391)s, %(product_name_m391)s, %(category_m391)s, %(sub_category_m391)s), (%(product_key_m392)s, %(product_id_m392)s, %(product_name_m392)s, %(category_m392)s, %(sub_category_m392)s), (%(product_key_m393)s, %(product_id_m393)s, %(product_name_m393)s, %(category_m393)s, %(sub_category_m393)s), (%(product_key_m394)s, %(product_id_m394)s, %(product_name_m394)s, %(category_m394)s, %(sub_category_m394)s), (%(product_key_m395)s, %(product_id_m395)s, %(product_name_m395)s, %(category_m395)s, %(sub_category_m395)s), (%(product_key_m396)s, %(product_id_m396)s, %(product_name_m396)s, %(category_m396)s, %(sub_category_m396)s), (%(product_key_m397)s, %(product_id_m397)s, %(product_name_m397)s, %(category_m397)s, %(sub_category_m397)s), (%(product_key_m398)s, %(product_id_m398)s, %(product_name_m398)s, %(category_m398)s, %(sub_category_m398)s), (%(product_key_m399)s, %(product_id_m399)s, %(product_name_m399)s, %(category_m399)s, %(sub_category_m399)s), (%(product_key_m400)s, %(product_id_m400)s, %(product_name_m400)s, %(category_m400)s, %(sub_category_m400)s), (%(product_key_m401)s, %(product_id_m401)s, %(product_name_m401)s, %(category_m401)s, %(sub_category_m401)s), (%(product_key_m402)s, %(product_id_m402)s, %(product_name_m402)s, %(category_m402)s, %(sub_category_m402)s), (%(product_key_m403)s, %(product_id_m403)s, %(product_name_m403)s, %(category_m403)s, %(sub_category_m403)s), (%(product_key_m404)s, %(product_id_m404)s, %(product_name_m404)s, %(category_m404)s, %(sub_category_m404)s), (%(product_key_m405)s, %(product_id_m405)s, %(product_name_m405)s, %(category_m405)s, %(sub_category_m405)s), (%(product_key_m406)s, %(product_id_m406)s, %(product_name_m406)s, %(category_m406)s, %(sub_category_m406)s), (%(product_key_m407)s, %(product_id_m407)s, %(product_name_m407)s, %(category_m407)s, %(sub_category_m407)s), (%(product_key_m408)s, %(product_id_m408)s, %(product_name_m408)s, %(category_m408)s, %(sub_category_m408)s), (%(product_key_m409)s, %(product_id_m409)s, %(product_name_m409)s, %(category_m409)s, %(sub_category_m409)s), (%(product_key_m410)s, %(product_id_m410)s, %(product_name_m410)s, %(category_m410)s, %(sub_category_m410)s), (%(product_key_m411)s, %(product_id_m411)s, %(product_name_m411)s, %(category_m411)s, %(sub_category_m411)s), (%(product_key_m412)s, %(product_id_m412)s, %(product_name_m412)s, %(category_m412)s, %(sub_category_m412)s), (%(product_key_m413)s, %(product_id_m413)s, %(product_name_m413)s, %(category_m413)s, %(sub_category_m413)s), (%(product_key_m414)s, %(product_id_m414)s, %(product_name_m414)s, %(category_m414)s, %(sub_category_m414)s), (%(product_key_m415)s, %(product_id_m415)s, %(product_name_m415)s, %(category_m415)s, %(sub_category_m415)s), (%(product_key_m416)s, %(product_id_m416)s, %(product_name_m416)s, %(category_m416)s, %(sub_category_m416)s), (%(product_key_m417)s, %(product_id_m417)s, %(product_name_m417)s, %(category_m417)s, %(sub_category_m417)s), (%(product_key_m418)s, %(product_id_m418)s, %(product_name_m418)s, %(category_m418)s, %(sub_category_m418)s), (%(product_key_m419)s, %(product_id_m419)s, %(product_name_m419)s, %(category_m419)s, %(sub_category_m419)s), (%(product_key_m420)s, %(product_id_m420)s, %(product_name_m420)s, %(category_m420)s, %(sub_category_m420)s), (%(product_key_m421)s, %(product_id_m421)s, %(product_name_m421)s, %(category_m421)s, %(sub_category_m421)s), (%(product_key_m422)s, %(product_id_m422)s, %(product_name_m422)s, %(category_m422)s, %(sub_category_m422)s), (%(product_key_m423)s, %(product_id_m423)s, %(product_name_m423)s, %(category_m423)s, %(sub_category_m423)s), (%(product_key_m424)s, %(product_id_m424)s, %(product_name_m424)s, %(category_m424)s, %(sub_category_m424)s), (%(product_key_m425)s, %(product_id_m425)s, %(product_name_m425)s, %(category_m425)s, %(sub_category_m425)s), (%(product_key_m426)s, %(product_id_m426)s, %(product_name_m426)s, %(category_m426)s, %(sub_category_m426)s), (%(product_key_m427)s, %(product_id_m427)s, %(product_name_m427)s, %(category_m427)s, %(sub_category_m427)s), (%(product_key_m428)s, %(product_id_m428)s, %(product_name_m428)s, %(category_m428)s, %(sub_category_m428)s), (%(product_key_m429)s, %(product_id_m429)s, %(product_name_m429)s, %(category_m429)s, %(sub_category_m429)s), (%(product_key_m430)s, %(product_id_m430)s, %(product_name_m430)s, %(category_m430)s, %(sub_category_m430)s), (%(product_key_m431)s, %(product_id_m431)s, %(product_name_m431)s, %(category_m431)s, %(sub_category_m431)s), (%(product_key_m432)s, %(product_id_m432)s, %(product_name_m432)s, %(category_m432)s, %(sub_category_m432)s), (%(product_key_m433)s, %(product_id_m433)s, %(product_name_m433)s, %(category_m433)s, %(sub_category_m433)s), (%(product_key_m434)s, %(product_id_m434)s, %(product_name_m434)s, %(category_m434)s, %(sub_category_m434)s), (%(product_key_m435)s, %(product_id_m435)s, %(product_name_m435)s, %(category_m435)s, %(sub_category_m435)s), (%(product_key_m436)s, %(product_id_m436)s, %(product_name_m436)s, %(category_m436)s, %(sub_category_m436)s), (%(product_key_m437)s, %(product_id_m437)s, %(product_name_m437)s, %(category_m437)s, %(sub_category_m437)s), (%(product_key_m438)s, %(product_id_m438)s, %(product_name_m438)s, %(category_m438)s, %(sub_category_m438)s), (%(product_key_m439)s, %(product_id_m439)s, %(product_name_m439)s, %(category_m439)s, %(sub_category_m439)s), (%(product_key_m440)s, %(product_id_m440)s, %(product_name_m440)s, %(category_m440)s, %(sub_category_m440)s), (%(product_key_m441)s, %(product_id_m441)s, %(product_name_m441)s, %(category_m441)s, %(sub_category_m441)s), (%(product_key_m442)s, %(product_id_m442)s, %(product_name_m442)s, %(category_m442)s, %(sub_category_m442)s), (%(product_key_m443)s, %(product_id_m443)s, %(product_name_m443)s, %(category_m443)s, %(sub_category_m443)s), (%(product_key_m444)s, %(product_id_m444)s, %(product_name_m444)s, %(category_m444)s, %(sub_category_m444)s), (%(product_key_m445)s, %(product_id_m445)s, %(product_name_m445)s, %(category_m445)s, %(sub_category_m445)s), (%(product_key_m446)s, %(product_id_m446)s, %(product_name_m446)s, %(category_m446)s, %(sub_category_m446)s), (%(product_key_m447)s, %(product_id_m447)s, %(product_name_m447)s, %(category_m447)s, %(sub_category_m447)s), (%(product_key_m448)s, %(product_id_m448)s, %(product_name_m448)s, %(category_m448)s, %(sub_category_m448)s), (%(product_key_m449)s, %(product_id_m449)s, %(product_name_m449)s, %(category_m449)s, %(sub_category_m449)s), (%(product_key_m450)s, %(product_id_m450)s, %(product_name_m450)s, %(category_m450)s, %(sub_category_m450)s), (%(product_key_m451)s, %(product_id_m451)s, %(product_name_m451)s, %(category_m451)s, %(sub_category_m451)s), (%(product_key_m452)s, %(product_id_m452)s, %(product_name_m452)s, %(category_m452)s, %(sub_category_m452)s), (%(product_key_m453)s, %(product_id_m453)s, %(product_name_m453)s, %(category_m453)s, %(sub_category_m453)s), (%(product_key_m454)s, %(product_id_m454)s, %(product_name_m454)s, %(category_m454)s, %(sub_category_m454)s), (%(product_key_m455)s, %(product_id_m455)s, %(product_name_m455)s, %(category_m455)s, %(sub_category_m455)s), (%(product_key_m456)s, %(product_id_m456)s, %(product_name_m456)s, %(category_m456)s, %(sub_category_m456)s), (%(product_key_m457)s, %(product_id_m457)s, %(product_name_m457)s, %(category_m457)s, %(sub_category_m457)s), (%(product_key_m458)s, %(product_id_m458)s, %(product_name_m458)s, %(category_m458)s, %(sub_category_m458)s), (%(product_key_m459)s, %(product_id_m459)s, %(product_name_m459)s, %(category_m459)s, %(sub_category_m459)s), (%(product_key_m460)s, %(product_id_m460)s, %(product_name_m460)s, %(category_m460)s, %(sub_category_m460)s), (%(product_key_m461)s, %(product_id_m461)s, %(product_name_m461)s, %(category_m461)s, %(sub_category_m461)s), (%(product_key_m462)s, %(product_id_m462)s, %(product_name_m462)s, %(category_m462)s, %(sub_category_m462)s), (%(product_key_m463)s, %(product_id_m463)s, %(product_name_m463)s, %(category_m463)s, %(sub_category_m463)s), (%(product_key_m464)s, %(product_id_m464)s, %(product_name_m464)s, %(category_m464)s, %(sub_category_m464)s), (%(product_key_m465)s, %(product_id_m465)s, %(product_name_m465)s, %(category_m465)s, %(sub_category_m465)s), (%(product_key_m466)s, %(product_id_m466)s, %(product_name_m466)s, %(category_m466)s, %(sub_category_m466)s), (%(product_key_m467)s, %(product_id_m467)s, %(product_name_m467)s, %(category_m467)s, %(sub_category_m467)s), (%(product_key_m468)s, %(product_id_m468)s, %(product_name_m468)s, %(category_m468)s, %(sub_category_m468)s), (%(product_key_m469)s, %(product_id_m469)s, %(product_name_m469)s, %(category_m469)s, %(sub_category_m469)s), (%(product_key_m470)s, %(product_id_m470)s, %(product_name_m470)s, %(category_m470)s, %(sub_category_m470)s), (%(product_key_m471)s, %(product_id_m471)s, %(product_name_m471)s, %(category_m471)s, %(sub_category_m471)s), (%(product_key_m472)s, %(product_id_m472)s, %(product_name_m472)s, %(category_m472)s, %(sub_category_m472)s), (%(product_key_m473)s, %(product_id_m473)s, %(product_name_m473)s, %(category_m473)s, %(sub_category_m473)s), (%(product_key_m474)s, %(product_id_m474)s, %(product_name_m474)s, %(category_m474)s, %(sub_category_m474)s), (%(product_key_m475)s, %(product_id_m475)s, %(product_name_m475)s, %(category_m475)s, %(sub_category_m475)s), (%(product_key_m476)s, %(product_id_m476)s, %(product_name_m476)s, %(category_m476)s, %(sub_category_m476)s), (%(product_key_m477)s, %(product_id_m477)s, %(product_name_m477)s, %(category_m477)s, %(sub_category_m477)s), (%(product_key_m478)s, %(product_id_m478)s, %(product_name_m478)s, %(category_m478)s, %(sub_category_m478)s), (%(product_key_m479)s, %(product_id_m479)s, %(product_name_m479)s, %(category_m479)s, %(sub_category_m479)s), (%(product_key_m480)s, %(product_id_m480)s, %(product_name_m480)s, %(category_m480)s, %(sub_category_m480)s), (%(product_key_m481)s, %(product_id_m481)s, %(product_name_m481)s, %(category_m481)s, %(sub_category_m481)s), (%(product_key_m482)s, %(product_id_m482)s, %(product_name_m482)s, %(category_m482)s, %(sub_category_m482)s), (%(product_key_m483)s, %(product_id_m483)s, %(product_name_m483)s, %(category_m483)s, %(sub_category_m483)s), (%(product_key_m484)s, %(product_id_m484)s, %(product_name_m484)s, %(category_m484)s, %(sub_category_m484)s), (%(product_key_m485)s, %(product_id_m485)s, %(product_name_m485)s, %(category_m485)s, %(sub_category_m485)s), (%(product_key_m486)s, %(product_id_m486)s, %(product_name_m486)s, %(category_m486)s, %(sub_category_m486)s), (%(product_key_m487)s, %(product_id_m487)s, %(product_name_m487)s, %(category_m487)s, %(sub_category_m487)s), (%(product_key_m488)s, %(product_id_m488)s, %(product_name_m488)s, %(category_m488)s, %(sub_category_m488)s), (%(product_key_m489)s, %(product_id_m489)s, %(product_name_m489)s, %(category_m489)s, %(sub_category_m489)s), (%(product_key_m490)s, %(product_id_m490)s, %(product_name_m490)s, %(category_m490)s, %(sub_category_m490)s), (%(product_key_m491)s, %(product_id_m491)s, %(product_name_m491)s, %(category_m491)s, %(sub_category_m491)s), (%(product_key_m492)s, %(product_id_m492)s, %(product_name_m492)s, %(category_m492)s, %(sub_category_m492)s), (%(product_key_m493)s, %(product_id_m493)s, %(product_name_m493)s, %(category_m493)s, %(sub_category_m493)s), (%(product_key_m494)s, %(product_id_m494)s, %(product_name_m494)s, %(category_m494)s, %(sub_category_m494)s), (%(product_key_m495)s, %(product_id_m495)s, %(product_name_m495)s, %(category_m495)s, %(sub_category_m495)s), (%(product_key_m496)s, %(product_id_m496)s, %(product_name_m496)s, %(category_m496)s, %(sub_category_m496)s), (%(product_key_m497)s, %(product_id_m497)s, %(product_name_m497)s, %(category_m497)s, %(sub_category_m497)s), (%(product_key_m498)s, %(product_id_m498)s, %(product_name_m498)s, %(category_m498)s, %(sub_category_m498)s), (%(product_key_m499)s, %(product_id_m499)s, %(product_name_m499)s, %(category_m499)s, %(sub_category_m499)s), (%(product_key_m500)s, %(product_id_m500)s, %(product_name_m500)s, %(category_m500)s, %(sub_category_m500)s), (%(product_key_m501)s, %(product_id_m501)s, %(product_name_m501)s, %(category_m501)s, %(sub_category_m501)s), (%(product_key_m502)s, %(product_id_m502)s, %(product_name_m502)s, %(category_m502)s, %(sub_category_m502)s), (%(product_key_m503)s, %(product_id_m503)s, %(product_name_m503)s, %(category_m503)s, %(sub_category_m503)s), (%(product_key_m504)s, %(product_id_m504)s, %(product_name_m504)s, %(category_m504)s, %(sub_category_m504)s), (%(product_key_m505)s, %(product_id_m505)s, %(product_name_m505)s, %(category_m505)s, %(sub_category_m505)s), (%(product_key_m506)s, %(product_id_m506)s, %(product_name_m506)s, %(category_m506)s, %(sub_category_m506)s), (%(product_key_m507)s, %(product_id_m507)s, %(product_name_m507)s, %(category_m507)s, %(sub_category_m507)s), (%(product_key_m508)s, %(product_id_m508)s, %(product_name_m508)s, %(category_m508)s, %(sub_category_m508)s), (%(product_key_m509)s, %(product_id_m509)s, %(product_name_m509)s, %(category_m509)s, %(sub_category_m509)s), (%(product_key_m510)s, %(product_id_m510)s, %(product_name_m510)s, %(category_m510)s, %(sub_category_m510)s), (%(product_key_m511)s, %(product_id_m511)s, %(product_name_m511)s, %(category_m511)s, %(sub_category_m511)s), (%(product_key_m512)s, %(product_id_m512)s, %(product_name_m512)s, %(category_m512)s, %(sub_category_m512)s), (%(product_key_m513)s, %(product_id_m513)s, %(product_name_m513)s, %(category_m513)s, %(sub_category_m513)s), (%(product_key_m514)s, %(product_id_m514)s, %(product_name_m514)s, %(category_m514)s, %(sub_category_m514)s), (%(product_key_m515)s, %(product_id_m515)s, %(product_name_m515)s, %(category_m515)s, %(sub_category_m515)s), (%(product_key_m516)s, %(product_id_m516)s, %(product_name_m516)s, %(category_m516)s, %(sub_category_m516)s), (%(product_key_m517)s, %(product_id_m517)s, %(product_name_m517)s, %(category_m517)s, %(sub_category_m517)s), (%(product_key_m518)s, %(product_id_m518)s, %(product_name_m518)s, %(category_m518)s, %(sub_category_m518)s), (%(product_key_m519)s, %(product_id_m519)s, %(product_name_m519)s, %(category_m519)s, %(sub_category_m519)s), (%(product_key_m520)s, %(product_id_m520)s, %(product_name_m520)s, %(category_m520)s, %(sub_category_m520)s), (%(product_key_m521)s, %(product_id_m521)s, %(product_name_m521)s, %(category_m521)s, %(sub_category_m521)s), (%(product_key_m522)s, %(product_id_m522)s, %(product_name_m522)s, %(category_m522)s, %(sub_category_m522)s), (%(product_key_m523)s, %(product_id_m523)s, %(product_name_m523)s, %(category_m523)s, %(sub_category_m523)s), (%(product_key_m524)s, %(product_id_m524)s, %(product_name_m524)s, %(category_m524)s, %(sub_category_m524)s), (%(product_key_m525)s, %(product_id_m525)s, %(product_name_m525)s, %(category_m525)s, %(sub_category_m525)s), (%(product_key_m526)s, %(product_id_m526)s, %(product_name_m526)s, %(category_m526)s, %(sub_category_m526)s), (%(product_key_m527)s, %(product_id_m527)s, %(product_name_m527)s, %(category_m527)s, %(sub_category_m527)s), (%(product_key_m528)s, %(product_id_m528)s, %(product_name_m528)s, %(category_m528)s, %(sub_category_m528)s), (%(product_key_m529)s, %(product_id_m529)s, %(product_name_m529)s, %(category_m529)s, %(sub_category_m529)s), (%(product_key_m530)s, %(product_id_m530)s, %(product_name_m530)s, %(category_m530)s, %(sub_category_m530)s), (%(product_key_m531)s, %(product_id_m531)s, %(product_name_m531)s, %(category_m531)s, %(sub_category_m531)s), (%(product_key_m532)s, %(product_id_m532)s, %(product_name_m532)s, %(category_m532)s, %(sub_category_m532)s), (%(product_key_m533)s, %(product_id_m533)s, %(product_name_m533)s, %(category_m533)s, %(sub_category_m533)s), (%(product_key_m534)s, %(product_id_m534)s, %(product_name_m534)s, %(category_m534)s, %(sub_category_m534)s), (%(product_key_m535)s, %(product_id_m535)s, %(product_name_m535)s, %(category_m535)s, %(sub_category_m535)s), (%(product_key_m536)s, %(product_id_m536)s, %(product_name_m536)s, %(category_m536)s, %(sub_category_m536)s), (%(product_key_m537)s, %(product_id_m537)s, %(product_name_m537)s, %(category_m537)s, %(sub_category_m537)s), (%(product_key_m538)s, %(product_id_m538)s, %(product_name_m538)s, %(category_m538)s, %(sub_category_m538)s), (%(product_key_m539)s, %(product_id_m539)s, %(product_name_m539)s, %(category_m539)s, %(sub_category_m539)s), (%(product_key_m540)s, %(product_id_m540)s, %(product_name_m540)s, %(category_m540)s, %(sub_category_m540)s), (%(product_key_m541)s, %(product_id_m541)s, %(product_name_m541)s, %(category_m541)s, %(sub_category_m541)s), (%(product_key_m542)s, %(product_id_m542)s, %(product_name_m542)s, %(category_m542)s, %(sub_category_m542)s), (%(product_key_m543)s, %(product_id_m543)s, %(product_name_m543)s, %(category_m543)s, %(sub_category_m543)s), (%(product_key_m544)s, %(product_id_m544)s, %(product_name_m544)s, %(category_m544)s, %(sub_category_m544)s), (%(product_key_m545)s, %(product_id_m545)s, %(product_name_m545)s, %(category_m545)s, %(sub_category_m545)s), (%(product_key_m546)s, %(product_id_m546)s, %(product_name_m546)s, %(category_m546)s, %(sub_category_m546)s), (%(product_key_m547)s, %(product_id_m547)s, %(product_name_m547)s, %(category_m547)s, %(sub_category_m547)s), (%(product_key_m548)s, %(product_id_m548)s, %(product_name_m548)s, %(category_m548)s, %(sub_category_m548)s), (%(product_key_m549)s, %(product_id_m549)s, %(product_name_m549)s, %(category_m549)s, %(sub_category_m549)s), (%(product_key_m550)s, %(product_id_m550)s, %(product_name_m550)s, %(category_m550)s, %(sub_category_m550)s), (%(product_key_m551)s, %(product_id_m551)s, %(product_name_m551)s, %(category_m551)s, %(sub_category_m551)s), (%(product_key_m552)s, %(product_id_m552)s, %(product_name_m552)s, %(category_m552)s, %(sub_category_m552)s), (%(product_key_m553)s, %(product_id_m553)s, %(product_name_m553)s, %(category_m553)s, %(sub_category_m553)s), (%(product_key_m554)s, %(product_id_m554)s, %(product_name_m554)s, %(category_m554)s, %(sub_category_m554)s), (%(product_key_m555)s, %(product_id_m555)s, %(product_name_m555)s, %(category_m555)s, %(sub_category_m555)s), (%(product_key_m556)s, %(product_id_m556)s, %(product_name_m556)s, %(category_m556)s, %(sub_category_m556)s), (%(product_key_m557)s, %(product_id_m557)s, %(product_name_m557)s, %(category_m557)s, %(sub_category_m557)s), (%(product_key_m558)s, %(product_id_m558)s, %(product_name_m558)s, %(category_m558)s, %(sub_category_m558)s), (%(product_key_m559)s, %(product_id_m559)s, %(product_name_m559)s, %(category_m559)s, %(sub_category_m559)s), (%(product_key_m560)s, %(product_id_m560)s, %(product_name_m560)s, %(category_m560)s, %(sub_category_m560)s), (%(product_key_m561)s, %(product_id_m561)s, %(product_name_m561)s, %(category_m561)s, %(sub_category_m561)s), (%(product_key_m562)s, %(product_id_m562)s, %(product_name_m562)s, %(category_m562)s, %(sub_category_m562)s), (%(product_key_m563)s, %(product_id_m563)s, %(product_name_m563)s, %(category_m563)s, %(sub_category_m563)s), (%(product_key_m564)s, %(product_id_m564)s, %(product_name_m564)s, %(category_m564)s, %(sub_category_m564)s), (%(product_key_m565)s, %(product_id_m565)s, %(product_name_m565)s, %(category_m565)s, %(sub_category_m565)s), (%(product_key_m566)s, %(product_id_m566)s, %(product_name_m566)s, %(category_m566)s, %(sub_category_m566)s), (%(product_key_m567)s, %(product_id_m567)s, %(product_name_m567)s, %(category_m567)s, %(sub_category_m567)s), (%(product_key_m568)s, %(product_id_m568)s, %(product_name_m568)s, %(category_m568)s, %(sub_category_m568)s), (%(product_key_m569)s, %(product_id_m569)s, %(product_name_m569)s, %(category_m569)s, %(sub_category_m569)s), (%(product_key_m570)s, %(product_id_m570)s, %(product_name_m570)s, %(category_m570)s, %(sub_category_m570)s), (%(product_key_m571)s, %(product_id_m571)s, %(product_name_m571)s, %(category_m571)s, %(sub_category_m571)s), (%(product_key_m572)s, %(product_id_m572)s, %(product_name_m572)s, %(category_m572)s, %(sub_category_m572)s), (%(product_key_m573)s, %(product_id_m573)s, %(product_name_m573)s, %(category_m573)s, %(sub_category_m573)s), (%(product_key_m574)s, %(product_id_m574)s, %(product_name_m574)s, %(category_m574)s, %(sub_category_m574)s), (%(product_key_m575)s, %(product_id_m575)s, %(product_name_m575)s, %(category_m575)s, %(sub_category_m575)s), (%(product_key_m576)s, %(product_id_m576)s, %(product_name_m576)s, %(category_m576)s, %(sub_category_m576)s), (%(product_key_m577)s, %(product_id_m577)s, %(product_name_m577)s, %(category_m577)s, %(sub_category_m577)s), (%(product_key_m578)s, %(product_id_m578)s, %(product_name_m578)s, %(category_m578)s, %(sub_category_m578)s), (%(product_key_m579)s, %(product_id_m579)s, %(product_name_m579)s, %(category_m579)s, %(sub_category_m579)s), (%(product_key_m580)s, %(product_id_m580)s, %(product_name_m580)s, %(category_m580)s, %(sub_category_m580)s), (%(product_key_m581)s, %(product_id_m581)s, %(product_name_m581)s, %(category_m581)s, %(sub_category_m581)s), (%(product_key_m582)s, %(product_id_m582)s, %(product_name_m582)s, %(category_m582)s, %(sub_category_m582)s), (%(product_key_m583)s, %(product_id_m583)s, %(product_name_m583)s, %(category_m583)s, %(sub_category_m583)s), (%(product_key_m584)s, %(product_id_m584)s, %(product_name_m584)s, %(category_m584)s, %(sub_category_m584)s), (%(product_key_m585)s, %(product_id_m585)s, %(product_name_m585)s, %(category_m585)s, %(sub_category_m585)s), (%(product_key_m586)s, %(product_id_m586)s, %(product_name_m586)s, %(category_m586)s, %(sub_category_m586)s), (%(product_key_m587)s, %(product_id_m587)s, %(product_name_m587)s, %(category_m587)s, %(sub_category_m587)s), (%(product_key_m588)s, %(product_id_m588)s, %(product_name_m588)s, %(category_m588)s, %(sub_category_m588)s), (%(product_key_m589)s, %(product_id_m589)s, %(product_name_m589)s, %(category_m589)s, %(sub_category_m589)s), (%(product_key_m590)s, %(product_id_m590)s, %(product_name_m590)s, %(category_m590)s, %(sub_category_m590)s), (%(product_key_m591)s, %(product_id_m591)s, %(product_name_m591)s, %(category_m591)s, %(sub_category_m591)s), (%(product_key_m592)s, %(product_id_m592)s, %(product_name_m592)s, %(category_m592)s, %(sub_category_m592)s), (%(product_key_m593)s, %(product_id_m593)s, %(product_name_m593)s, %(category_m593)s, %(sub_category_m593)s), (%(product_key_m594)s, %(product_id_m594)s, %(product_name_m594)s, %(category_m594)s, %(sub_category_m594)s), (%(product_key_m595)s, %(product_id_m595)s, %(product_name_m595)s, %(category_m595)s, %(sub_category_m595)s), (%(product_key_m596)s, %(product_id_m596)s, %(product_name_m596)s, %(category_m596)s, %(sub_category_m596)s), (%(product_key_m597)s, %(product_id_m597)s, %(product_name_m597)s, %(category_m597)s, %(sub_category_m597)s), (%(product_key_m598)s, %(product_id_m598)s, %(product_name_m598)s, %(category_m598)s, %(sub_category_m598)s), (%(product_key_m599)s, %(product_id_m599)s, %(product_name_m599)s, %(category_m599)s, %(sub_category_m599)s), (%(product_key_m600)s, %(product_id_m600)s, %(product_name_m600)s, %(category_m600)s, %(sub_category_m600)s), (%(product_key_m601)s, %(product_id_m601)s, %(product_name_m601)s, %(category_m601)s, %(sub_category_m601)s), (%(product_key_m602)s, %(product_id_m602)s, %(product_name_m602)s, %(category_m602)s, %(sub_category_m602)s), (%(product_key_m603)s, %(product_id_m603)s, %(product_name_m603)s, %(category_m603)s, %(sub_category_m603)s), (%(product_key_m604)s, %(product_id_m604)s, %(product_name_m604)s, %(category_m604)s, %(sub_category_m604)s), (%(product_key_m605)s, %(product_id_m605)s, %(product_name_m605)s, %(category_m605)s, %(sub_category_m605)s), (%(product_key_m606)s, %(product_id_m606)s, %(product_name_m606)s, %(category_m606)s, %(sub_category_m606)s), (%(product_key_m607)s, %(product_id_m607)s, %(product_name_m607)s, %(category_m607)s, %(sub_category_m607)s), (%(product_key_m608)s, %(product_id_m608)s, %(product_name_m608)s, %(category_m608)s, %(sub_category_m608)s), (%(product_key_m609)s, %(product_id_m609)s, %(product_name_m609)s, %(category_m609)s, %(sub_category_m609)s), (%(product_key_m610)s, %(product_id_m610)s, %(product_name_m610)s, %(category_m610)s, %(sub_category_m610)s), (%(product_key_m611)s, %(product_id_m611)s, %(product_name_m611)s, %(category_m611)s, %(sub_category_m611)s), (%(product_key_m612)s, %(product_id_m612)s, %(product_name_m612)s, %(category_m612)s, %(sub_category_m612)s), (%(product_key_m613)s, %(product_id_m613)s, %(product_name_m613)s, %(category_m613)s, %(sub_category_m613)s), (%(product_key_m614)s, %(product_id_m614)s, %(product_name_m614)s, %(category_m614)s, %(sub_category_m614)s), (%(product_key_m615)s, %(product_id_m615)s, %(product_name_m615)s, %(category_m615)s, %(sub_category_m615)s), (%(product_key_m616)s, %(product_id_m616)s, %(product_name_m616)s, %(category_m616)s, %(sub_category_m616)s), (%(product_key_m617)s, %(product_id_m617)s, %(product_name_m617)s, %(category_m617)s, %(sub_category_m617)s), (%(product_key_m618)s, %(product_id_m618)s, %(product_name_m618)s, %(category_m618)s, %(sub_category_m618)s), (%(product_key_m619)s, %(product_id_m619)s, %(product_name_m619)s, %(category_m619)s, %(sub_category_m619)s), (%(product_key_m620)s, %(product_id_m620)s, %(product_name_m620)s, %(category_m620)s, %(sub_category_m620)s), (%(product_key_m621)s, %(product_id_m621)s, %(product_name_m621)s, %(category_m621)s, %(sub_category_m621)s), (%(product_key_m622)s, %(product_id_m622)s, %(product_name_m622)s, %(category_m622)s, %(sub_category_m622)s), (%(product_key_m623)s, %(product_id_m623)s, %(product_name_m623)s, %(category_m623)s, %(sub_category_m623)s), (%(product_key_m624)s, %(product_id_m624)s, %(product_name_m624)s, %(category_m624)s, %(sub_category_m624)s), (%(product_key_m625)s, %(product_id_m625)s, %(product_name_m625)s, %(category_m625)s, %(sub_category_m625)s), (%(product_key_m626)s, %(product_id_m626)s, %(product_name_m626)s, %(category_m626)s, %(sub_category_m626)s), (%(product_key_m627)s, %(product_id_m627)s, %(product_name_m627)s, %(category_m627)s, %(sub_category_m627)s), (%(product_key_m628)s, %(product_id_m628)s, %(product_name_m628)s, %(category_m628)s, %(sub_category_m628)s), (%(product_key_m629)s, %(product_id_m629)s, %(product_name_m629)s, %(category_m629)s, %(sub_category_m629)s), (%(product_key_m630)s, %(product_id_m630)s, %(product_name_m630)s, %(category_m630)s, %(sub_category_m630)s), (%(product_key_m631)s, %(product_id_m631)s, %(product_name_m631)s, %(category_m631)s, %(sub_category_m631)s), (%(product_key_m632)s, %(product_id_m632)s, %(product_name_m632)s, %(category_m632)s, %(sub_category_m632)s), (%(product_key_m633)s, %(product_id_m633)s, %(product_name_m633)s, %(category_m633)s, %(sub_category_m633)s), (%(product_key_m634)s, %(product_id_m634)s, %(product_name_m634)s, %(category_m634)s, %(sub_category_m634)s), (%(product_key_m635)s, %(product_id_m635)s, %(product_name_m635)s, %(category_m635)s, %(sub_category_m635)s), (%(product_key_m636)s, %(product_id_m636)s, %(product_name_m636)s, %(category_m636)s, %(sub_category_m636)s), (%(product_key_m637)s, %(product_id_m637)s, %(product_name_m637)s, %(category_m637)s, %(sub_category_m637)s), (%(product_key_m638)s, %(product_id_m638)s, %(product_name_m638)s, %(category_m638)s, %(sub_category_m638)s), (%(product_key_m639)s, %(product_id_m639)s, %(product_name_m639)s, %(category_m639)s, %(sub_category_m639)s), (%(product_key_m640)s, %(product_id_m640)s, %(product_name_m640)s, %(category_m640)s, %(sub_category_m640)s), (%(product_key_m641)s, %(product_id_m641)s, %(product_name_m641)s, %(category_m641)s, %(sub_category_m641)s), (%(product_key_m642)s, %(product_id_m642)s, %(product_name_m642)s, %(category_m642)s, %(sub_category_m642)s), (%(product_key_m643)s, %(product_id_m643)s, %(product_name_m643)s, %(category_m643)s, %(sub_category_m643)s), (%(product_key_m644)s, %(product_id_m644)s, %(product_name_m644)s, %(category_m644)s, %(sub_category_m644)s), (%(product_key_m645)s, %(product_id_m645)s, %(product_name_m645)s, %(category_m645)s, %(sub_category_m645)s), (%(product_key_m646)s, %(product_id_m646)s, %(product_name_m646)s, %(category_m646)s, %(sub_category_m646)s), (%(product_key_m647)s, %(product_id_m647)s, %(product_name_m647)s, %(category_m647)s, %(sub_category_m647)s), (%(product_key_m648)s, %(product_id_m648)s, %(product_name_m648)s, %(category_m648)s, %(sub_category_m648)s), (%(product_key_m649)s, %(product_id_m649)s, %(product_name_m649)s, %(category_m649)s, %(sub_category_m649)s), (%(product_key_m650)s, %(product_id_m650)s, %(product_name_m650)s, %(category_m650)s, %(sub_category_m650)s), (%(product_key_m651)s, %(product_id_m651)s, %(product_name_m651)s, %(category_m651)s, %(sub_category_m651)s), (%(product_key_m652)s, %(product_id_m652)s, %(product_name_m652)s, %(category_m652)s, %(sub_category_m652)s), (%(product_key_m653)s, %(product_id_m653)s, %(product_name_m653)s, %(category_m653)s, %(sub_category_m653)s), (%(product_key_m654)s, %(product_id_m654)s, %(product_name_m654)s, %(category_m654)s, %(sub_category_m654)s), (%(product_key_m655)s, %(product_id_m655)s, %(product_name_m655)s, %(category_m655)s, %(sub_category_m655)s), (%(product_key_m656)s, %(product_id_m656)s, %(product_name_m656)s, %(category_m656)s, %(sub_category_m656)s), (%(product_key_m657)s, %(product_id_m657)s, %(product_name_m657)s, %(category_m657)s, %(sub_category_m657)s), (%(product_key_m658)s, %(product_id_m658)s, %(product_name_m658)s, %(category_m658)s, %(sub_category_m658)s), (%(product_key_m659)s, %(product_id_m659)s, %(product_name_m659)s, %(category_m659)s, %(sub_category_m659)s), (%(product_key_m660)s, %(product_id_m660)s, %(product_name_m660)s, %(category_m660)s, %(sub_category_m660)s), (%(product_key_m661)s, %(product_id_m661)s, %(product_name_m661)s, %(category_m661)s, %(sub_category_m661)s), (%(product_key_m662)s, %(product_id_m662)s, %(product_name_m662)s, %(category_m662)s, %(sub_category_m662)s), (%(product_key_m663)s, %(product_id_m663)s, %(product_name_m663)s, %(category_m663)s, %(sub_category_m663)s), (%(product_key_m664)s, %(product_id_m664)s, %(product_name_m664)s, %(category_m664)s, %(sub_category_m664)s), (%(product_key_m665)s, %(product_id_m665)s, %(product_name_m665)s, %(category_m665)s, %(sub_category_m665)s), (%(product_key_m666)s, %(product_id_m666)s, %(product_name_m666)s, %(category_m666)s, %(sub_category_m666)s), (%(product_key_m667)s, %(product_id_m667)s, %(product_name_m667)s, %(category_m667)s, %(sub_category_m667)s), (%(product_key_m668)s, %(product_id_m668)s, %(product_name_m668)s, %(category_m668)s, %(sub_category_m668)s), (%(product_key_m669)s, %(product_id_m669)s, %(product_name_m669)s, %(category_m669)s, %(sub_category_m669)s), (%(product_key_m670)s, %(product_id_m670)s, %(product_name_m670)s, %(category_m670)s, %(sub_category_m670)s), (%(product_key_m671)s, %(product_id_m671)s, %(product_name_m671)s, %(category_m671)s, %(sub_category_m671)s), (%(product_key_m672)s, %(product_id_m672)s, %(product_name_m672)s, %(category_m672)s, %(sub_category_m672)s), (%(product_key_m673)s, %(product_id_m673)s, %(product_name_m673)s, %(category_m673)s, %(sub_category_m673)s), (%(product_key_m674)s, %(product_id_m674)s, %(product_name_m674)s, %(category_m674)s, %(sub_category_m674)s), (%(product_key_m675)s, %(product_id_m675)s, %(product_name_m675)s, %(category_m675)s, %(sub_category_m675)s), (%(product_key_m676)s, %(product_id_m676)s, %(product_name_m676)s, %(category_m676)s, %(sub_category_m676)s), (%(product_key_m677)s, %(product_id_m677)s, %(product_name_m677)s, %(category_m677)s, %(sub_category_m677)s), (%(product_key_m678)s, %(product_id_m678)s, %(product_name_m678)s, %(category_m678)s, %(sub_category_m678)s), (%(product_key_m679)s, %(product_id_m679)s, %(product_name_m679)s, %(category_m679)s, %(sub_category_m679)s), (%(product_key_m680)s, %(product_id_m680)s, %(product_name_m680)s, %(category_m680)s, %(sub_category_m680)s), (%(product_key_m681)s, %(product_id_m681)s, %(product_name_m681)s, %(category_m681)s, %(sub_category_m681)s), (%(product_key_m682)s, %(product_id_m682)s, %(product_name_m682)s, %(category_m682)s, %(sub_category_m682)s), (%(product_key_m683)s, %(product_id_m683)s, %(product_name_m683)s, %(category_m683)s, %(sub_category_m683)s), (%(product_key_m684)s, %(product_id_m684)s, %(product_name_m684)s, %(category_m684)s, %(sub_category_m684)s), (%(product_key_m685)s, %(product_id_m685)s, %(product_name_m685)s, %(category_m685)s, %(sub_category_m685)s), (%(product_key_m686)s, %(product_id_m686)s, %(product_name_m686)s, %(category_m686)s, %(sub_category_m686)s), (%(product_key_m687)s, %(product_id_m687)s, %(product_name_m687)s, %(category_m687)s, %(sub_category_m687)s), (%(product_key_m688)s, %(product_id_m688)s, %(product_name_m688)s, %(category_m688)s, %(sub_category_m688)s), (%(product_key_m689)s, %(product_id_m689)s, %(product_name_m689)s, %(category_m689)s, %(sub_category_m689)s), (%(product_key_m690)s, %(product_id_m690)s, %(product_name_m690)s, %(category_m690)s, %(sub_category_m690)s), (%(product_key_m691)s, %(product_id_m691)s, %(product_name_m691)s, %(category_m691)s, %(sub_category_m691)s), (%(product_key_m692)s, %(product_id_m692)s, %(product_name_m692)s, %(category_m692)s, %(sub_category_m692)s), (%(product_key_m693)s, %(product_id_m693)s, %(product_name_m693)s, %(category_m693)s, %(sub_category_m693)s), (%(product_key_m694)s, %(product_id_m694)s, %(product_name_m694)s, %(category_m694)s, %(sub_category_m694)s), (%(product_key_m695)s, %(product_id_m695)s, %(product_name_m695)s, %(category_m695)s, %(sub_category_m695)s), (%(product_key_m696)s, %(product_id_m696)s, %(product_name_m696)s, %(category_m696)s, %(sub_category_m696)s), (%(product_key_m697)s, %(product_id_m697)s, %(product_name_m697)s, %(category_m697)s, %(sub_category_m697)s), (%(product_key_m698)s, %(product_id_m698)s, %(product_name_m698)s, %(category_m698)s, %(sub_category_m698)s), (%(product_key_m699)s, %(product_id_m699)s, %(product_name_m699)s, %(category_m699)s, %(sub_category_m699)s), (%(product_key_m700)s, %(product_id_m700)s, %(product_name_m700)s, %(category_m700)s, %(sub_category_m700)s), (%(product_key_m701)s, %(product_id_m701)s, %(product_name_m701)s, %(category_m701)s, %(sub_category_m701)s), (%(product_key_m702)s, %(product_id_m702)s, %(product_name_m702)s, %(category_m702)s, %(sub_category_m702)s), (%(product_key_m703)s, %(product_id_m703)s, %(product_name_m703)s, %(category_m703)s, %(sub_category_m703)s), (%(product_key_m704)s, %(product_id_m704)s, %(product_name_m704)s, %(category_m704)s, %(sub_category_m704)s), (%(product_key_m705)s, %(product_id_m705)s, %(product_name_m705)s, %(category_m705)s, %(sub_category_m705)s), (%(product_key_m706)s, %(product_id_m706)s, %(product_name_m706)s, %(category_m706)s, %(sub_category_m706)s), (%(product_key_m707)s, %(product_id_m707)s, %(product_name_m707)s, %(category_m707)s, %(sub_category_m707)s), (%(product_key_m708)s, %(product_id_m708)s, %(product_name_m708)s, %(category_m708)s, %(sub_category_m708)s), (%(product_key_m709)s, %(product_id_m709)s, %(product_name_m709)s, %(category_m709)s, %(sub_category_m709)s), (%(product_key_m710)s, %(product_id_m710)s, %(product_name_m710)s, %(category_m710)s, %(sub_category_m710)s), (%(product_key_m711)s, %(product_id_m711)s, %(product_name_m711)s, %(category_m711)s, %(sub_category_m711)s), (%(product_key_m712)s, %(product_id_m712)s, %(product_name_m712)s, %(category_m712)s, %(sub_category_m712)s), (%(product_key_m713)s, %(product_id_m713)s, %(product_name_m713)s, %(category_m713)s, %(sub_category_m713)s), (%(product_key_m714)s, %(product_id_m714)s, %(product_name_m714)s, %(category_m714)s, %(sub_category_m714)s), (%(product_key_m715)s, %(product_id_m715)s, %(product_name_m715)s, %(category_m715)s, %(sub_category_m715)s), (%(product_key_m716)s, %(product_id_m716)s, %(product_name_m716)s, %(category_m716)s, %(sub_category_m716)s), (%(product_key_m717)s, %(product_id_m717)s, %(product_name_m717)s, %(category_m717)s, %(sub_category_m717)s), (%(product_key_m718)s, %(product_id_m718)s, %(product_name_m718)s, %(category_m718)s, %(sub_category_m718)s), (%(product_key_m719)s, %(product_id_m719)s, %(product_name_m719)s, %(category_m719)s, %(sub_category_m719)s), (%(product_key_m720)s, %(product_id_m720)s, %(product_name_m720)s, %(category_m720)s, %(sub_category_m720)s), (%(product_key_m721)s, %(product_id_m721)s, %(product_name_m721)s, %(category_m721)s, %(sub_category_m721)s), (%(product_key_m722)s, %(product_id_m722)s, %(product_name_m722)s, %(category_m722)s, %(sub_category_m722)s), (%(product_key_m723)s, %(product_id_m723)s, %(product_name_m723)s, %(category_m723)s, %(sub_category_m723)s), (%(product_key_m724)s, %(product_id_m724)s, %(product_name_m724)s, %(category_m724)s, %(sub_category_m724)s), (%(product_key_m725)s, %(product_id_m725)s, %(product_name_m725)s, %(category_m725)s, %(sub_category_m725)s), (%(product_key_m726)s, %(product_id_m726)s, %(product_name_m726)s, %(category_m726)s, %(sub_category_m726)s), (%(product_key_m727)s, %(product_id_m727)s, %(product_name_m727)s, %(category_m727)s, %(sub_category_m727)s), (%(product_key_m728)s, %(product_id_m728)s, %(product_name_m728)s, %(category_m728)s, %(sub_category_m728)s), (%(product_key_m729)s, %(product_id_m729)s, %(product_name_m729)s, %(category_m729)s, %(sub_category_m729)s), (%(product_key_m730)s, %(product_id_m730)s, %(product_name_m730)s, %(category_m730)s, %(sub_category_m730)s), (%(product_key_m731)s, %(product_id_m731)s, %(product_name_m731)s, %(category_m731)s, %(sub_category_m731)s), (%(product_key_m732)s, %(product_id_m732)s, %(product_name_m732)s, %(category_m732)s, %(sub_category_m732)s), (%(product_key_m733)s, %(product_id_m733)s, %(product_name_m733)s, %(category_m733)s, %(sub_category_m733)s), (%(product_key_m734)s, %(product_id_m734)s, %(product_name_m734)s, %(category_m734)s, %(sub_category_m734)s), (%(product_key_m735)s, %(product_id_m735)s, %(product_name_m735)s, %(category_m735)s, %(sub_category_m735)s), (%(product_key_m736)s, %(product_id_m736)s, %(product_name_m736)s, %(category_m736)s, %(sub_category_m736)s), (%(product_key_m737)s, %(product_id_m737)s, %(product_name_m737)s, %(category_m737)s, %(sub_category_m737)s), (%(product_key_m738)s, %(product_id_m738)s, %(product_name_m738)s, %(category_m738)s, %(sub_category_m738)s), (%(product_key_m739)s, %(product_id_m739)s, %(product_name_m739)s, %(category_m739)s, %(sub_category_m739)s), (%(product_key_m740)s, %(product_id_m740)s, %(product_name_m740)s, %(category_m740)s, %(sub_category_m740)s), (%(product_key_m741)s, %(product_id_m741)s, %(product_name_m741)s, %(category_m741)s, %(sub_category_m741)s), (%(product_key_m742)s, %(product_id_m742)s, %(product_name_m742)s, %(category_m742)s, %(sub_category_m742)s), (%(product_key_m743)s, %(product_id_m743)s, %(product_name_m743)s, %(category_m743)s, %(sub_category_m743)s), (%(product_key_m744)s, %(product_id_m744)s, %(product_name_m744)s, %(category_m744)s, %(sub_category_m744)s), (%(product_key_m745)s, %(product_id_m745)s, %(product_name_m745)s, %(category_m745)s, %(sub_category_m745)s), (%(product_key_m746)s, %(product_id_m746)s, %(product_name_m746)s, %(category_m746)s, %(sub_category_m746)s), (%(product_key_m747)s, %(product_id_m747)s, %(product_name_m747)s, %(category_m747)s, %(sub_category_m747)s), (%(product_key_m748)s, %(product_id_m748)s, %(product_name_m748)s, %(category_m748)s, %(sub_category_m748)s), (%(product_key_m749)s, %(product_id_m749)s, %(product_name_m749)s, %(category_m749)s, %(sub_category_m749)s), (%(product_key_m750)s, %(product_id_m750)s, %(product_name_m750)s, %(category_m750)s, %(sub_category_m750)s), (%(product_key_m751)s, %(product_id_m751)s, %(product_name_m751)s, %(category_m751)s, %(sub_category_m751)s), (%(product_key_m752)s, %(product_id_m752)s, %(product_name_m752)s, %(category_m752)s, %(sub_category_m752)s), (%(product_key_m753)s, %(product_id_m753)s, %(product_name_m753)s, %(category_m753)s, %(sub_category_m753)s), (%(product_key_m754)s, %(product_id_m754)s, %(product_name_m754)s, %(category_m754)s, %(sub_category_m754)s), (%(product_key_m755)s, %(product_id_m755)s, %(product_name_m755)s, %(category_m755)s, %(sub_category_m755)s), (%(product_key_m756)s, %(product_id_m756)s, %(product_name_m756)s, %(category_m756)s, %(sub_category_m756)s), (%(product_key_m757)s, %(product_id_m757)s, %(product_name_m757)s, %(category_m757)s, %(sub_category_m757)s), (%(product_key_m758)s, %(product_id_m758)s, %(product_name_m758)s, %(category_m758)s, %(sub_category_m758)s), (%(product_key_m759)s, %(product_id_m759)s, %(product_name_m759)s, %(category_m759)s, %(sub_category_m759)s), (%(product_key_m760)s, %(product_id_m760)s, %(product_name_m760)s, %(category_m760)s, %(sub_category_m760)s), (%(product_key_m761)s, %(product_id_m761)s, %(product_name_m761)s, %(category_m761)s, %(sub_category_m761)s), (%(product_key_m762)s, %(product_id_m762)s, %(product_name_m762)s, %(category_m762)s, %(sub_category_m762)s), (%(product_key_m763)s, %(product_id_m763)s, %(product_name_m763)s, %(category_m763)s, %(sub_category_m763)s), (%(product_key_m764)s, %(product_id_m764)s, %(product_name_m764)s, %(category_m764)s, %(sub_category_m764)s), (%(product_key_m765)s, %(product_id_m765)s, %(product_name_m765)s, %(category_m765)s, %(sub_category_m765)s), (%(product_key_m766)s, %(product_id_m766)s, %(product_name_m766)s, %(category_m766)s, %(sub_category_m766)s), (%(product_key_m767)s, %(product_id_m767)s, %(product_name_m767)s, %(category_m767)s, %(sub_category_m767)s), (%(product_key_m768)s, %(product_id_m768)s, %(product_name_m768)s, %(category_m768)s, %(sub_category_m768)s), (%(product_key_m769)s, %(product_id_m769)s, %(product_name_m769)s, %(category_m769)s, %(sub_category_m769)s), (%(product_key_m770)s, %(product_id_m770)s, %(product_name_m770)s, %(category_m770)s, %(sub_category_m770)s), (%(product_key_m771)s, %(product_id_m771)s, %(product_name_m771)s, %(category_m771)s, %(sub_category_m771)s), (%(product_key_m772)s, %(product_id_m772)s, %(product_name_m772)s, %(category_m772)s, %(sub_category_m772)s), (%(product_key_m773)s, %(product_id_m773)s, %(product_name_m773)s, %(category_m773)s, %(sub_category_m773)s), (%(product_key_m774)s, %(product_id_m774)s, %(product_name_m774)s, %(category_m774)s, %(sub_category_m774)s), (%(product_key_m775)s, %(product_id_m775)s, %(product_name_m775)s, %(category_m775)s, %(sub_category_m775)s), (%(product_key_m776)s, %(product_id_m776)s, %(product_name_m776)s, %(category_m776)s, %(sub_category_m776)s), (%(product_key_m777)s, %(product_id_m777)s, %(product_name_m777)s, %(category_m777)s, %(sub_category_m777)s), (%(product_key_m778)s, %(product_id_m778)s, %(product_name_m778)s, %(category_m778)s, %(sub_category_m778)s), (%(product_key_m779)s, %(product_id_m779)s, %(product_name_m779)s, %(category_m779)s, %(sub_category_m779)s), (%(product_key_m780)s, %(product_id_m780)s, %(product_name_m780)s, %(category_m780)s, %(sub_category_m780)s), (%(product_key_m781)s, %(product_id_m781)s, %(product_name_m781)s, %(category_m781)s, %(sub_category_m781)s), (%(product_key_m782)s, %(product_id_m782)s, %(product_name_m782)s, %(category_m782)s, %(sub_category_m782)s), (%(product_key_m783)s, %(product_id_m783)s, %(product_name_m783)s, %(category_m783)s, %(sub_category_m783)s), (%(product_key_m784)s, %(product_id_m784)s, %(product_name_m784)s, %(category_m784)s, %(sub_category_m784)s), (%(product_key_m785)s, %(product_id_m785)s, %(product_name_m785)s, %(category_m785)s, %(sub_category_m785)s), (%(product_key_m786)s, %(product_id_m786)s, %(product_name_m786)s, %(category_m786)s, %(sub_category_m786)s), (%(product_key_m787)s, %(product_id_m787)s, %(product_name_m787)s, %(category_m787)s, %(sub_category_m787)s), (%(product_key_m788)s, %(product_id_m788)s, %(product_name_m788)s, %(category_m788)s, %(sub_category_m788)s), (%(product_key_m789)s, %(product_id_m789)s, %(product_name_m789)s, %(category_m789)s, %(sub_category_m789)s), (%(product_key_m790)s, %(product_id_m790)s, %(product_name_m790)s, %(category_m790)s, %(sub_category_m790)s), (%(product_key_m791)s, %(product_id_m791)s, %(product_name_m791)s, %(category_m791)s, %(sub_category_m791)s), (%(product_key_m792)s, %(product_id_m792)s, %(product_name_m792)s, %(category_m792)s, %(sub_category_m792)s), (%(product_key_m793)s, %(product_id_m793)s, %(product_name_m793)s, %(category_m793)s, %(sub_category_m793)s), (%(product_key_m794)s, %(product_id_m794)s, %(product_name_m794)s, %(category_m794)s, %(sub_category_m794)s), (%(product_key_m795)s, %(product_id_m795)s, %(product_name_m795)s, %(category_m795)s, %(sub_category_m795)s), (%(product_key_m796)s, %(product_id_m796)s, %(product_name_m796)s, %(category_m796)s, %(sub_category_m796)s), (%(product_key_m797)s, %(product_id_m797)s, %(product_name_m797)s, %(category_m797)s, %(sub_category_m797)s), (%(product_key_m798)s, %(product_id_m798)s, %(product_name_m798)s, %(category_m798)s, %(sub_category_m798)s), (%(product_key_m799)s, %(product_id_m799)s, %(product_name_m799)s, %(category_m799)s, %(sub_category_m799)s), (%(product_key_m800)s, %(product_id_m800)s, %(product_name_m800)s, %(category_m800)s, %(sub_category_m800)s), (%(product_key_m801)s, %(product_id_m801)s, %(product_name_m801)s, %(category_m801)s, %(sub_category_m801)s), (%(product_key_m802)s, %(product_id_m802)s, %(product_name_m802)s, %(category_m802)s, %(sub_category_m802)s), (%(product_key_m803)s, %(product_id_m803)s, %(product_name_m803)s, %(category_m803)s, %(sub_category_m803)s), (%(product_key_m804)s, %(product_id_m804)s, %(product_name_m804)s, %(category_m804)s, %(sub_category_m804)s), (%(product_key_m805)s, %(product_id_m805)s, %(product_name_m805)s, %(category_m805)s, %(sub_category_m805)s), (%(product_key_m806)s, %(product_id_m806)s, %(product_name_m806)s, %(category_m806)s, %(sub_category_m806)s), (%(product_key_m807)s, %(product_id_m807)s, %(product_name_m807)s, %(category_m807)s, %(sub_category_m807)s), (%(product_key_m808)s, %(product_id_m808)s, %(product_name_m808)s, %(category_m808)s, %(sub_category_m808)s), (%(product_key_m809)s, %(product_id_m809)s, %(product_name_m809)s, %(category_m809)s, %(sub_category_m809)s), (%(product_key_m810)s, %(product_id_m810)s, %(product_name_m810)s, %(category_m810)s, %(sub_category_m810)s), (%(product_key_m811)s, %(product_id_m811)s, %(product_name_m811)s, %(category_m811)s, %(sub_category_m811)s), (%(product_key_m812)s, %(product_id_m812)s, %(product_name_m812)s, %(category_m812)s, %(sub_category_m812)s), (%(product_key_m813)s, %(product_id_m813)s, %(product_name_m813)s, %(category_m813)s, %(sub_category_m813)s), (%(product_key_m814)s, %(product_id_m814)s, %(product_name_m814)s, %(category_m814)s, %(sub_category_m814)s), (%(product_key_m815)s, %(product_id_m815)s, %(product_name_m815)s, %(category_m815)s, %(sub_category_m815)s), (%(product_key_m816)s, %(product_id_m816)s, %(product_name_m816)s, %(category_m816)s, %(sub_category_m816)s), (%(product_key_m817)s, %(product_id_m817)s, %(product_name_m817)s, %(category_m817)s, %(sub_category_m817)s), (%(product_key_m818)s, %(product_id_m818)s, %(product_name_m818)s, %(category_m818)s, %(sub_category_m818)s), (%(product_key_m819)s, %(product_id_m819)s, %(product_name_m819)s, %(category_m819)s, %(sub_category_m819)s), (%(product_key_m820)s, %(product_id_m820)s, %(product_name_m820)s, %(category_m820)s, %(sub_category_m820)s), (%(product_key_m821)s, %(product_id_m821)s, %(product_name_m821)s, %(category_m821)s, %(sub_category_m821)s), (%(product_key_m822)s, %(product_id_m822)s, %(product_name_m822)s, %(category_m822)s, %(sub_category_m822)s), (%(product_key_m823)s, %(product_id_m823)s, %(product_name_m823)s, %(category_m823)s, %(sub_category_m823)s), (%(product_key_m824)s, %(product_id_m824)s, %(product_name_m824)s, %(category_m824)s, %(sub_category_m824)s), (%(product_key_m825)s, %(product_id_m825)s, %(product_name_m825)s, %(category_m825)s, %(sub_category_m825)s), (%(product_key_m826)s, %(product_id_m826)s, %(product_name_m826)s, %(category_m826)s, %(sub_category_m826)s), (%(product_key_m827)s, %(product_id_m827)s, %(product_name_m827)s, %(category_m827)s, %(sub_category_m827)s), (%(product_key_m828)s, %(product_id_m828)s, %(product_name_m828)s, %(category_m828)s, %(sub_category_m828)s), (%(product_key_m829)s, %(product_id_m829)s, %(product_name_m829)s, %(category_m829)s, %(sub_category_m829)s), (%(product_key_m830)s, %(product_id_m830)s, %(product_name_m830)s, %(category_m830)s, %(sub_category_m830)s), (%(product_key_m831)s, %(product_id_m831)s, %(product_name_m831)s, %(category_m831)s, %(sub_category_m831)s), (%(product_key_m832)s, %(product_id_m832)s, %(product_name_m832)s, %(category_m832)s, %(sub_category_m832)s), (%(product_key_m833)s, %(product_id_m833)s, %(product_name_m833)s, %(category_m833)s, %(sub_category_m833)s), (%(product_key_m834)s, %(product_id_m834)s, %(product_name_m834)s, %(category_m834)s, %(sub_category_m834)s), (%(product_key_m835)s, %(product_id_m835)s, %(product_name_m835)s, %(category_m835)s, %(sub_category_m835)s), (%(product_key_m836)s, %(product_id_m836)s, %(product_name_m836)s, %(category_m836)s, %(sub_category_m836)s), (%(product_key_m837)s, %(product_id_m837)s, %(product_name_m837)s, %(category_m837)s, %(sub_category_m837)s), (%(product_key_m838)s, %(product_id_m838)s, %(product_name_m838)s, %(category_m838)s, %(sub_category_m838)s), (%(product_key_m839)s, %(product_id_m839)s, %(product_name_m839)s, %(category_m839)s, %(sub_category_m839)s), (%(product_key_m840)s, %(product_id_m840)s, %(product_name_m840)s, %(category_m840)s, %(sub_category_m840)s), (%(product_key_m841)s, %(product_id_m841)s, %(product_name_m841)s, %(category_m841)s, %(sub_category_m841)s), (%(product_key_m842)s, %(product_id_m842)s, %(product_name_m842)s, %(category_m842)s, %(sub_category_m842)s), (%(product_key_m843)s, %(product_id_m843)s, %(product_name_m843)s, %(category_m843)s, %(sub_category_m843)s), (%(product_key_m844)s, %(product_id_m844)s, %(product_name_m844)s, %(category_m844)s, %(sub_category_m844)s), (%(product_key_m845)s, %(product_id_m845)s, %(product_name_m845)s, %(category_m845)s, %(sub_category_m845)s), (%(product_key_m846)s, %(product_id_m846)s, %(product_name_m846)s, %(category_m846)s, %(sub_category_m846)s), (%(product_key_m847)s, %(product_id_m847)s, %(product_name_m847)s, %(category_m847)s, %(sub_category_m847)s), (%(product_key_m848)s, %(product_id_m848)s, %(product_name_m848)s, %(category_m848)s, %(sub_category_m848)s), (%(product_key_m849)s, %(product_id_m849)s, %(product_name_m849)s, %(category_m849)s, %(sub_category_m849)s), (%(product_key_m850)s, %(product_id_m850)s, %(product_name_m850)s, %(category_m850)s, %(sub_category_m850)s), (%(product_key_m851)s, %(product_id_m851)s, %(product_name_m851)s, %(category_m851)s, %(sub_category_m851)s), (%(product_key_m852)s, %(product_id_m852)s, %(product_name_m852)s, %(category_m852)s, %(sub_category_m852)s), (%(product_key_m853)s, %(product_id_m853)s, %(product_name_m853)s, %(category_m853)s, %(sub_category_m853)s), (%(product_key_m854)s, %(product_id_m854)s, %(product_name_m854)s, %(category_m854)s, %(sub_category_m854)s), (%(product_key_m855)s, %(product_id_m855)s, %(product_name_m855)s, %(category_m855)s, %(sub_category_m855)s), (%(product_key_m856)s, %(product_id_m856)s, %(product_name_m856)s, %(category_m856)s, %(sub_category_m856)s), (%(product_key_m857)s, %(product_id_m857)s, %(product_name_m857)s, %(category_m857)s, %(sub_category_m857)s), (%(product_key_m858)s, %(product_id_m858)s, %(product_name_m858)s, %(category_m858)s, %(sub_category_m858)s), (%(product_key_m859)s, %(product_id_m859)s, %(product_name_m859)s, %(category_m859)s, %(sub_category_m859)s), (%(product_key_m860)s, %(product_id_m860)s, %(product_name_m860)s, %(category_m860)s, %(sub_category_m860)s), (%(product_key_m861)s, %(product_id_m861)s, %(product_name_m861)s, %(category_m861)s, %(sub_category_m861)s), (%(product_key_m862)s, %(product_id_m862)s, %(product_name_m862)s, %(category_m862)s, %(sub_category_m862)s), (%(product_key_m863)s, %(product_id_m863)s, %(product_name_m863)s, %(category_m863)s, %(sub_category_m863)s), (%(product_key_m864)s, %(product_id_m864)s, %(product_name_m864)s, %(category_m864)s, %(sub_category_m864)s), (%(product_key_m865)s, %(product_id_m865)s, %(product_name_m865)s, %(category_m865)s, %(sub_category_m865)s), (%(product_key_m866)s, %(product_id_m866)s, %(product_name_m866)s, %(category_m866)s, %(sub_category_m866)s), (%(product_key_m867)s, %(product_id_m867)s, %(product_name_m867)s, %(category_m867)s, %(sub_category_m867)s), (%(product_key_m868)s, %(product_id_m868)s, %(product_name_m868)s, %(category_m868)s, %(sub_category_m868)s), (%(product_key_m869)s, %(product_id_m869)s, %(product_name_m869)s, %(category_m869)s, %(sub_category_m869)s), (%(product_key_m870)s, %(product_id_m870)s, %(product_name_m870)s, %(category_m870)s, %(sub_category_m870)s), (%(product_key_m871)s, %(product_id_m871)s, %(product_name_m871)s, %(category_m871)s, %(sub_category_m871)s), (%(product_key_m872)s, %(product_id_m872)s, %(product_name_m872)s, %(category_m872)s, %(sub_category_m872)s), (%(product_key_m873)s, %(product_id_m873)s, %(product_name_m873)s, %(category_m873)s, %(sub_category_m873)s), (%(product_key_m874)s, %(product_id_m874)s, %(product_name_m874)s, %(category_m874)s, %(sub_category_m874)s), (%(product_key_m875)s, %(product_id_m875)s, %(product_name_m875)s, %(category_m875)s, %(sub_category_m875)s), (%(product_key_m876)s, %(product_id_m876)s, %(product_name_m876)s, %(category_m876)s, %(sub_category_m876)s), (%(product_key_m877)s, %(product_id_m877)s, %(product_name_m877)s, %(category_m877)s, %(sub_category_m877)s), (%(product_key_m878)s, %(product_id_m878)s, %(product_name_m878)s, %(category_m878)s, %(sub_category_m878)s), (%(product_key_m879)s, %(product_id_m879)s, %(product_name_m879)s, %(category_m879)s, %(sub_category_m879)s), (%(product_key_m880)s, %(product_id_m880)s, %(product_name_m880)s, %(category_m880)s, %(sub_category_m880)s), (%(product_key_m881)s, %(product_id_m881)s, %(product_name_m881)s, %(category_m881)s, %(sub_category_m881)s), (%(product_key_m882)s, %(product_id_m882)s, %(product_name_m882)s, %(category_m882)s, %(sub_category_m882)s), (%(product_key_m883)s, %(product_id_m883)s, %(product_name_m883)s, %(category_m883)s, %(sub_category_m883)s), (%(product_key_m884)s, %(product_id_m884)s, %(product_name_m884)s, %(category_m884)s, %(sub_category_m884)s), (%(product_key_m885)s, %(product_id_m885)s, %(product_name_m885)s, %(category_m885)s, %(sub_category_m885)s), (%(product_key_m886)s, %(product_id_m886)s, %(product_name_m886)s, %(category_m886)s, %(sub_category_m886)s), (%(product_key_m887)s, %(product_id_m887)s, %(product_name_m887)s, %(category_m887)s, %(sub_category_m887)s), (%(product_key_m888)s, %(product_id_m888)s, %(product_name_m888)s, %(category_m888)s, %(sub_category_m888)s), (%(product_key_m889)s, %(product_id_m889)s, %(product_name_m889)s, %(category_m889)s, %(sub_category_m889)s), (%(product_key_m890)s, %(product_id_m890)s, %(product_name_m890)s, %(category_m890)s, %(sub_category_m890)s), (%(product_key_m891)s, %(product_id_m891)s, %(product_name_m891)s, %(category_m891)s, %(sub_category_m891)s), (%(product_key_m892)s, %(product_id_m892)s, %(product_name_m892)s, %(category_m892)s, %(sub_category_m892)s), (%(product_key_m893)s, %(product_id_m893)s, %(product_name_m893)s, %(category_m893)s, %(sub_category_m893)s), (%(product_key_m894)s, %(product_id_m894)s, %(product_name_m894)s, %(category_m894)s, %(sub_category_m894)s), (%(product_key_m895)s, %(product_id_m895)s, %(product_name_m895)s, %(category_m895)s, %(sub_category_m895)s), (%(product_key_m896)s, %(product_id_m896)s, %(product_name_m896)s, %(category_m896)s, %(sub_category_m896)s), (%(product_key_m897)s, %(product_id_m897)s, %(product_name_m897)s, %(category_m897)s, %(sub_category_m897)s), (%(product_key_m898)s, %(product_id_m898)s, %(product_name_m898)s, %(category_m898)s, %(sub_category_m898)s), (%(product_key_m899)s, %(product_id_m899)s, %(product_name_m899)s, %(category_m899)s, %(sub_category_m899)s), (%(product_key_m900)s, %(product_id_m900)s, %(product_name_m900)s, %(category_m900)s, %(sub_category_m900)s), (%(product_key_m901)s, %(product_id_m901)s, %(product_name_m901)s, %(category_m901)s, %(sub_category_m901)s), (%(product_key_m902)s, %(product_id_m902)s, %(product_name_m902)s, %(category_m902)s, %(sub_category_m902)s), (%(product_key_m903)s, %(product_id_m903)s, %(product_name_m903)s, %(category_m903)s, %(sub_category_m903)s), (%(product_key_m904)s, %(product_id_m904)s, %(product_name_m904)s, %(category_m904)s, %(sub_category_m904)s), (%(product_key_m905)s, %(product_id_m905)s, %(product_name_m905)s, %(category_m905)s, %(sub_category_m905)s), (%(product_key_m906)s, %(product_id_m906)s, %(product_name_m906)s, %(category_m906)s, %(sub_category_m906)s), (%(product_key_m907)s, %(product_id_m907)s, %(product_name_m907)s, %(category_m907)s, %(sub_category_m907)s), (%(product_key_m908)s, %(product_id_m908)s, %(product_name_m908)s, %(category_m908)s, %(sub_category_m908)s), (%(product_key_m909)s, %(product_id_m909)s, %(product_name_m909)s, %(category_m909)s, %(sub_category_m909)s), (%(product_key_m910)s, %(product_id_m910)s, %(product_name_m910)s, %(category_m910)s, %(sub_category_m910)s), (%(product_key_m911)s, %(product_id_m911)s, %(product_name_m911)s, %(category_m911)s, %(sub_category_m911)s), (%(product_key_m912)s, %(product_id_m912)s, %(product_name_m912)s, %(category_m912)s, %(sub_category_m912)s), (%(product_key_m913)s, %(product_id_m913)s, %(product_name_m913)s, %(category_m913)s, %(sub_category_m913)s), (%(product_key_m914)s, %(product_id_m914)s, %(product_name_m914)s, %(category_m914)s, %(sub_category_m914)s), (%(product_key_m915)s, %(product_id_m915)s, %(product_name_m915)s, %(category_m915)s, %(sub_category_m915)s), (%(product_key_m916)s, %(product_id_m916)s, %(product_name_m916)s, %(category_m916)s, %(sub_category_m916)s), (%(product_key_m917)s, %(product_id_m917)s, %(product_name_m917)s, %(category_m917)s, %(sub_category_m917)s), (%(product_key_m918)s, %(product_id_m918)s, %(product_name_m918)s, %(category_m918)s, %(sub_category_m918)s), (%(product_key_m919)s, %(product_id_m919)s, %(product_name_m919)s, %(category_m919)s, %(sub_category_m919)s), (%(product_key_m920)s, %(product_id_m920)s, %(product_name_m920)s, %(category_m920)s, %(sub_category_m920)s), (%(product_key_m921)s, %(product_id_m921)s, %(product_name_m921)s, %(category_m921)s, %(sub_category_m921)s), (%(product_key_m922)s, %(product_id_m922)s, %(product_name_m922)s, %(category_m922)s, %(sub_category_m922)s), (%(product_key_m923)s, %(product_id_m923)s, %(product_name_m923)s, %(category_m923)s, %(sub_category_m923)s), (%(product_key_m924)s, %(product_id_m924)s, %(product_name_m924)s, %(category_m924)s, %(sub_category_m924)s), (%(product_key_m925)s, %(product_id_m925)s, %(product_name_m925)s, %(category_m925)s, %(sub_category_m925)s), (%(product_key_m926)s, %(product_id_m926)s, %(product_name_m926)s, %(category_m926)s, %(sub_category_m926)s), (%(product_key_m927)s, %(product_id_m927)s, %(product_name_m927)s, %(category_m927)s, %(sub_category_m927)s), (%(product_key_m928)s, %(product_id_m928)s, %(product_name_m928)s, %(category_m928)s, %(sub_category_m928)s), (%(product_key_m929)s, %(product_id_m929)s, %(product_name_m929)s, %(category_m929)s, %(sub_category_m929)s), (%(product_key_m930)s, %(product_id_m930)s, %(product_name_m930)s, %(category_m930)s, %(sub_category_m930)s), (%(product_key_m931)s, %(product_id_m931)s, %(product_name_m931)s, %(category_m931)s, %(sub_category_m931)s), (%(product_key_m932)s, %(product_id_m932)s, %(product_name_m932)s, %(category_m932)s, %(sub_category_m932)s), (%(product_key_m933)s, %(product_id_m933)s, %(product_name_m933)s, %(category_m933)s, %(sub_category_m933)s), (%(product_key_m934)s, %(product_id_m934)s, %(product_name_m934)s, %(category_m934)s, %(sub_category_m934)s), (%(product_key_m935)s, %(product_id_m935)s, %(product_name_m935)s, %(category_m935)s, %(sub_category_m935)s), (%(product_key_m936)s, %(product_id_m936)s, %(product_name_m936)s, %(category_m936)s, %(sub_category_m936)s), (%(product_key_m937)s, %(product_id_m937)s, %(product_name_m937)s, %(category_m937)s, %(sub_category_m937)s), (%(product_key_m938)s, %(product_id_m938)s, %(product_name_m938)s, %(category_m938)s, %(sub_category_m938)s), (%(product_key_m939)s, %(product_id_m939)s, %(product_name_m939)s, %(category_m939)s, %(sub_category_m939)s), (%(product_key_m940)s, %(product_id_m940)s, %(product_name_m940)s, %(category_m940)s, %(sub_category_m940)s), (%(product_key_m941)s, %(product_id_m941)s, %(product_name_m941)s, %(category_m941)s, %(sub_category_m941)s), (%(product_key_m942)s, %(product_id_m942)s, %(product_name_m942)s, %(category_m942)s, %(sub_category_m942)s), (%(product_key_m943)s, %(product_id_m943)s, %(product_name_m943)s, %(category_m943)s, %(sub_category_m943)s), (%(product_key_m944)s, %(product_id_m944)s, %(product_name_m944)s, %(category_m944)s, %(sub_category_m944)s), (%(product_key_m945)s, %(product_id_m945)s, %(product_name_m945)s, %(category_m945)s, %(sub_category_m945)s), (%(product_key_m946)s, %(product_id_m946)s, %(product_name_m946)s, %(category_m946)s, %(sub_category_m946)s), (%(product_key_m947)s, %(product_id_m947)s, %(product_name_m947)s, %(category_m947)s, %(sub_category_m947)s), (%(product_key_m948)s, %(product_id_m948)s, %(product_name_m948)s, %(category_m948)s, %(sub_category_m948)s), (%(product_key_m949)s, %(product_id_m949)s, %(product_name_m949)s, %(category_m949)s, %(sub_category_m949)s), (%(product_key_m950)s, %(product_id_m950)s, %(product_name_m950)s, %(category_m950)s, %(sub_category_m950)s), (%(product_key_m951)s, %(product_id_m951)s, %(product_name_m951)s, %(category_m951)s, %(sub_category_m951)s), (%(product_key_m952)s, %(product_id_m952)s, %(product_name_m952)s, %(category_m952)s, %(sub_category_m952)s), (%(product_key_m953)s, %(product_id_m953)s, %(product_name_m953)s, %(category_m953)s, %(sub_category_m953)s), (%(product_key_m954)s, %(product_id_m954)s, %(product_name_m954)s, %(category_m954)s, %(sub_category_m954)s), (%(product_key_m955)s, %(product_id_m955)s, %(product_name_m955)s, %(category_m955)s, %(sub_category_m955)s), (%(product_key_m956)s, %(product_id_m956)s, %(product_name_m956)s, %(category_m956)s, %(sub_category_m956)s), (%(product_key_m957)s, %(product_id_m957)s, %(product_name_m957)s, %(category_m957)s, %(sub_category_m957)s), (%(product_key_m958)s, %(product_id_m958)s, %(product_name_m958)s, %(category_m958)s, %(sub_category_m958)s), (%(product_key_m959)s, %(product_id_m959)s, %(product_name_m959)s, %(category_m959)s, %(sub_category_m959)s), (%(product_key_m960)s, %(product_id_m960)s, %(product_name_m960)s, %(category_m960)s, %(sub_category_m960)s), (%(product_key_m961)s, %(product_id_m961)s, %(product_name_m961)s, %(category_m961)s, %(sub_category_m961)s), (%(product_key_m962)s, %(product_id_m962)s, %(product_name_m962)s, %(category_m962)s, %(sub_category_m962)s), (%(product_key_m963)s, %(product_id_m963)s, %(product_name_m963)s, %(category_m963)s, %(sub_category_m963)s), (%(product_key_m964)s, %(product_id_m964)s, %(product_name_m964)s, %(category_m964)s, %(sub_category_m964)s), (%(product_key_m965)s, %(product_id_m965)s, %(product_name_m965)s, %(category_m965)s, %(sub_category_m965)s), (%(product_key_m966)s, %(product_id_m966)s, %(product_name_m966)s, %(category_m966)s, %(sub_category_m966)s), (%(product_key_m967)s, %(product_id_m967)s, %(product_name_m967)s, %(category_m967)s, %(sub_category_m967)s), (%(product_key_m968)s, %(product_id_m968)s, %(product_name_m968)s, %(category_m968)s, %(sub_category_m968)s), (%(product_key_m969)s, %(product_id_m969)s, %(product_name_m969)s, %(category_m969)s, %(sub_category_m969)s), (%(product_key_m970)s, %(product_id_m970)s, %(product_name_m970)s, %(category_m970)s, %(sub_category_m970)s), (%(product_key_m971)s, %(product_id_m971)s, %(product_name_m971)s, %(category_m971)s, %(sub_category_m971)s), (%(product_key_m972)s, %(product_id_m972)s, %(product_name_m972)s, %(category_m972)s, %(sub_category_m972)s), (%(product_key_m973)s, %(product_id_m973)s, %(product_name_m973)s, %(category_m973)s, %(sub_category_m973)s), (%(product_key_m974)s, %(product_id_m974)s, %(product_name_m974)s, %(category_m974)s, %(sub_category_m974)s), (%(product_key_m975)s, %(product_id_m975)s, %(product_name_m975)s, %(category_m975)s, %(sub_category_m975)s), (%(product_key_m976)s, %(product_id_m976)s, %(product_name_m976)s, %(category_m976)s, %(sub_category_m976)s), (%(product_key_m977)s, %(product_id_m977)s, %(product_name_m977)s, %(category_m977)s, %(sub_category_m977)s), (%(product_key_m978)s, %(product_id_m978)s, %(product_name_m978)s, %(category_m978)s, %(sub_category_m978)s), (%(product_key_m979)s, %(product_id_m979)s, %(product_name_m979)s, %(category_m979)s, %(sub_category_m979)s), (%(product_key_m980)s, %(product_id_m980)s, %(product_name_m980)s, %(category_m980)s, %(sub_category_m980)s), (%(product_key_m981)s, %(product_id_m981)s, %(product_name_m981)s, %(category_m981)s, %(sub_category_m981)s), (%(product_key_m982)s, %(product_id_m982)s, %(product_name_m982)s, %(category_m982)s, %(sub_category_m982)s), (%(product_key_m983)s, %(product_id_m983)s, %(product_name_m983)s, %(category_m983)s, %(sub_category_m983)s), (%(product_key_m984)s, %(product_id_m984)s, %(product_name_m984)s, %(category_m984)s, %(sub_category_m984)s), (%(product_key_m985)s, %(product_id_m985)s, %(product_name_m985)s, %(category_m985)s, %(sub_category_m985)s), (%(product_key_m986)s, %(product_id_m986)s, %(product_name_m986)s, %(category_m986)s, %(sub_category_m986)s), (%(product_key_m987)s, %(product_id_m987)s, %(product_name_m987)s, %(category_m987)s, %(sub_category_m987)s), (%(product_key_m988)s, %(product_id_m988)s, %(product_name_m988)s, %(category_m988)s, %(sub_category_m988)s), (%(product_key_m989)s, %(product_id_m989)s, %(product_name_m989)s, %(category_m989)s, %(sub_category_m989)s), (%(product_key_m990)s, %(product_id_m990)s, %(product_name_m990)s, %(category_m990)s, %(sub_category_m990)s), (%(product_key_m991)s, %(product_id_m991)s, %(product_name_m991)s, %(category_m991)s, %(sub_category_m991)s), (%(product_key_m992)s, %(product_id_m992)s, %(product_name_m992)s, %(category_m992)s, %(sub_category_m992)s), (%(product_key_m993)s, %(product_id_m993)s, %(product_name_m993)s, %(category_m993)s, %(sub_category_m993)s), (%(product_key_m994)s, %(product_id_m994)s, %(product_name_m994)s, %(category_m994)s, %(sub_category_m994)s), (%(product_key_m995)s, %(product_id_m995)s, %(product_name_m995)s, %(category_m995)s, %(sub_category_m995)s), (%(product_key_m996)s, %(product_id_m996)s, %(product_name_m996)s, %(category_m996)s, %(sub_category_m996)s), (%(product_key_m997)s, %(product_id_m997)s, %(product_name_m997)s, %(category_m997)s, %(sub_category_m997)s), (%(product_key_m998)s, %(product_id_m998)s, %(product_name_m998)s, %(category_m998)s, %(sub_category_m998)s), (%(product_key_m999)s, %(product_id_m999)s, %(product_name_m999)s, %(category_m999)s, %(sub_category_m999)s)]
[parameters: {'product_key_m0': 1, 'product_id_m0': 'FUR-BO-10001798', 'product_name_m0': 'Bush Somerset Collection Bookcase', 'category_m0': 'Furniture', 'sub_category_m0': 'Bookcases', 'product_key_m1': 2, 'product_id_m1': 'FUR-CH-10000454', 'product_name_m1': 'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back', 'category_m1': 'Furniture', 'sub_category_m1': 'Chairs', 'product_key_m2': 3, 'product_id_m2': 'OFF-LA-10000240', 'product_name_m2': 'Self-Adhesive Address Labels for Typewriters by Universal', 'category_m2': 'Office Supplies', 'sub_category_m2': 'Labels', 'product_key_m3': 4, 'product_id_m3': 'FUR-TA-10000577', 'product_name_m3': 'Bretford CR4500 Series Slim Rectangular Table', 'category_m3': 'Furniture', 'sub_category_m3': 'Tables', 'product_key_m4': 5, 'product_id_m4': 'OFF-ST-10000760', 'product_name_m4': "Eldon Fold 'N Roll Cart System", 'category_m4': 'Office Supplies', 'sub_category_m4': 'Storage', 'product_key_m5': 6, 'product_id_m5': 'FUR-FU-10001487', 'product_name_m5': 'Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood', 'category_m5': 'Furniture', 'sub_category_m5': 'Furnishings', 'product_key_m6': 7, 'product_id_m6': 'OFF-AR-10002833', 'product_name_m6': 'Newell 322', 'category_m6': 'Office Supplies', 'sub_category_m6': 'Art', 'product_key_m7': 8, 'product_id_m7': 'TEC-PH-10002275', 'product_name_m7': 'Mitel 5320 IP Phone VoIP phone', 'category_m7': 'Technology', 'sub_category_m7': 'Phones', 'product_key_m8': 9, 'product_id_m8': 'OFF-BI-10003910', 'product_name_m8': 'DXL Angle-View Binders with Locking Rings by Samsill', 'category_m8': 'Office Supplies', 'sub_category_m8': 'Binders', 'product_key_m9': 10, 'product_id_m9': 'OFF-AP-10002892', 'product_name_m9': 'Belkin F5C206VTEL 6 Outlet Surge', 'category_m9': 'Office Supplies', 'sub_category_m9': 'Appliances' ... 4900 parameters truncated ... 'product_key_m990': 991, 'product_id_m990': 'TEC-PH-10002922', 'product_name_m990': 'ShoreTel ShorePhone IP 230 VoIP phone', 'category_m990': 'Technology', 'sub_category_m990': 'Phones', 'product_key_m991': 992, 'product_id_m991': 'OFF-PA-10000501', 'product_name_m991': 'Petty Cash Envelope', 'category_m991': 'Office Supplies', 'sub_category_m991': 'Paper', 'product_key_m992': 993, 'product_id_m992': 'OFF-AP-10004980', 'product_name_m992': "3M Replacement Filter for Office Air Cleaner for 20' x 33' Room", 'category_m992': 'Office Supplies', 'sub_category_m992': 'Appliances', 'product_key_m993': 994, 'product_id_m993': 'TEC-PH-10001750', 'product_name_m993': 'Samsung Rugby III', 'category_m993': 'Technology', 'sub_category_m993': 'Phones', 'product_key_m994': 995, 'product_id_m994': 'OFF-BI-10003708', 'product_name_m994': 'Acco Four Pocket Poly Ring Binder with Label Holder, Smoke, 1"', 'category_m994': 'Office Supplies', 'sub_category_m994': 'Binders', 'product_key_m995': 996, 'product_id_m995': 'OFF-BI-10001191', 'product_name_m995': 'Canvas Sectional Post Binders', 'category_m995': 'Office Supplies', 'sub_category_m995': 'Binders', 'product_key_m996': 997, 'product_id_m996': 'OFF-PA-10003673', 'product_name_m996': 'Strathmore Photo Mount Cards', 'category_m996': 'Office Supplies', 'sub_category_m996': 'Paper', 'product_key_m997': 998, 'product_id_m997': 'OFF-PA-10001639', 'product_name_m997': 'Xerox 203', 'category_m997': 'Office Supplies', 'sub_category_m997': 'Paper', 'product_key_m998': 999, 'product_id_m998': 'TEC-AC-10004975', 'product_name_m998': 'Plantronics Audio 995 Wireless Stereo Headset', 'category_m998': 'Technology', 'sub_category_m998': 'Accessories', 'product_key_m999': 1000, 'product_id_m999': 'OFF-BI-10004364', 'product_name_m999': 'Storex Dura Pro Binders', 'category_m999': 'Office Supplies', 'sub_category_m999': 'Binders'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [41]:
db_utils.run_pg_query("""
ALTER TABLE superstore.products
ALTER COLUMN product_key
SET GENERATED BY DEFAULT;
""")

'Execution successful. Rows affected: -1'

In [42]:
db_utils.run_pg_query("""
SELECT
    column_name,
    is_identity,
    identity_generation
FROM information_schema.columns
WHERE table_schema = 'superstore'
AND table_name = 'products'
AND column_name = 'product_key';
""")

,column_name,is_identity,identity_generation
0,product_key,YES,BY DEFAULT


In [43]:
products_df.to_sql(
    "products",
    con=postgres_engine,
    schema="superstore",
    if_exists="append",
    index=False,
    chunksize=1000,
    method="multi"
)

1894

In [44]:
db_utils.run_pg_query("""
SELECT
    COUNT(*) AS product_count,
    MIN(product_key) AS min_product_key,
    MAX(product_key) AS max_product_key
FROM superstore.products;
""")

,product_count,min_product_key,max_product_key
0,1894,1,1894


In [45]:
db_utils.run_pg_query("""
SELECT setval(
    pg_get_serial_sequence('superstore.products', 'product_key'),
    (SELECT MAX(product_key) FROM superstore.products)
);
""")

,setval
0,1894


In [46]:
db_utils.run_pg_query("""
SELECT
    COUNT(*) AS product_count,
    MIN(product_key) AS min_key,
    MAX(product_key) AS max_key
FROM superstore.products;
""")

,product_count,min_key,max_key
0,1894,1,1894


In [47]:
orders_df.to_sql(
    "orders",
    con=postgres_engine,
    schema="superstore",
    if_exists="append",
    index=False,
    chunksize=1000,
    method="multi"
)

5009

In [48]:
db_utils.run_pg_query("""
SELECT COUNT(*) AS product_count
FROM superstore.products;
""")

,product_count
0,1894


In [49]:
order_items_df.to_sql(
    "order_items",
    con=postgres_engine,
    schema="superstore",
    if_exists="append",
    index=False,
    chunksize=1000,
    method="multi"
)

9994

In [50]:
db_utils.run_pg_query("""
SELECT COUNT(*) AS order_item_count
FROM superstore.order_items;
""")

,order_item_count
0,9994


In [51]:
mysql_totals = pd.read_sql("""
SELECT
    SUM(sales) AS sales,
    SUM(quantity) AS quantity,
    SUM(discount) AS discount,
    SUM(profit) AS profit
FROM Order_Items;
""", mysql_engine)

postgres_totals = pd.read_sql("""
SELECT
    SUM(sales) AS sales,
    SUM(quantity) AS quantity,
    SUM(discount) AS discount,
    SUM(profit) AS profit
FROM superstore.order_items;
""", postgres_engine)

print("MYSQL")
display(mysql_totals)

print("POSTGRESQL")
display(postgres_totals)

MYSQL


,sales,quantity,discount,profit
0,2297201.07,37873.0,1561.09,286397.0217


POSTGRESQL


,sales,quantity,discount,profit
0,2297201.07,37873,1561.09,286397.0217


In [52]:
comparison = pd.DataFrame({
    "MySQL": mysql_totals.iloc[0],
    "PostgreSQL": postgres_totals.iloc[0]
})

comparison["Difference"] = (
    comparison["PostgreSQL"] - comparison["MySQL"]
)

display(comparison)

,MySQL,PostgreSQL,Difference
sales,2.297201e+06,2.297201e+06,0.0
quantity,3.787300e+04,3.787300e+04,0.0
discount,1.561090e+03,1.561090e+03,0.0
profit,2.863970e+05,2.863970e+05,0.0


## BUSINESS CASE 1: ARE WE ACTUALLY MAKING MONEY?

### Management Request

> "Give me a high-level performance overview of the business. I want to know how much revenue we've generated, how much profit we've made, and our overall profit margin."

In [6]:
query = """
SELECT
    SUM(sales) AS "Total Revenue",
    SUM(profit) AS "Total Profit",
    ROUND(
        (SUM(profit) / NULLIF(SUM(sales), 0)) * 100,
        2
    ) AS "Profit Margin %"
FROM superstore.order_items;
"""

In [7]:
db_utils.run_pg_query(query)

,Total Revenue,Total Profit,Profit Margin %
0,2297201.07,286397.0217,12.47


### Performance Summary

* **Total Revenue:** $2,297,201.07
* **Total Profit:** $286,397.02
* **Profit Margin:** 12.47%

> **Key Takeaway:** The business remains profitable with a **12.47%** margin, yielding **$286,397.02** in net profit from **$2.30M** in revenue.

## BUSINESS CASE 2: PRODUCT PERFORMANCE ANALYSIS

### Management Request
> "Which product categories are driving our profitability, and which ones should we be concerned about?"

---

### Executive Performance Breakdown

| Category | Total Revenue | Total Profit | Profit Margin % | Status |
| :--- | :--- | :--- | :--- | :--- |
| **Technology** | $836,154.10 | $145,454.95 | 17.40% | 🟢 Top Driver |
| **Office Supplies** | $719,046.99 | $122,490.80 | 17.04% | 🟢 Strong Performer |
| **Furniture** | $741,999.98 | $18,451.27 | 2.49% | 🔴 High Concern |

---

### Key Takeaways & Strategic Recommendations

* **Drivers of Profitability:** **Technology** and **Office Supplies** drive **93.5%** of the business's total profits, maintaining strong profit margins near **17%**.
* **Primary Concern:** **Furniture** is severely underperforming. Despite bringing in **$741.99K** in revenue, it yields only **$18.45K** in profit (**2.49%** margin). 
* **Next Steps:** Investigate discounting patterns, shipping/logistics costs, and product-level margins within the Furniture sub-categories to identify where margins are being eroded.

In [8]:
query2 = """
SELECT
    p.category AS Category,
    SUM(o.sales) AS "Total Revenue",
    SUM(o.profit) AS "Total Profit",
    ROUND(
        (SUM(o.profit) / NULLIF(SUM(o.sales), 0)) * 100,
        2
    ) AS "Profit Margin %"
FROM superstore.order_items o
JOIN superstore.products p
    ON p.product_key = o.product_key
GROUP BY p.category;
"""

db_utils.run_pg_query(query2)

,category,Total Revenue,Total Profit,Profit Margin %
0,Furniture,741999.98,18451.2728,2.49
1,Office Supplies,719046.99,122490.8008,17.04
2,Technology,836154.10,145454.9481,17.40


## BUSINESS CASE 3: INVESTIGATING FURNITURE SUB-CATEGORIES

### Management Request
> "Furniture has a much lower profit margin than the other categories. Find out which sub-categories are responsible for this poor performance."

---

### Furniture Sub-Category Performance

| Sub-Category | Total Revenue | Total Profit | Profit Margin % | Status |
| :--- | :--- | :--- | :--- | :--- |
| **Furnishings** | $91,705.12 | $13,059.14 | 14.24% | 🟢 Healthy |
| **Chairs** | $328,449.13 | $26,590.17 | 8.10% | 🟡 Moderate |
| **Bookcases** | $114,880.05 | -$3,472.56 | -3.02% | 🔴 Net Loss |
| **Tables** | $206,965.68 | -$17,725.48 | -8.56% | 🔴 Major Drag |

---

### Key Findings & Root Cause

* **Root Cause Identified:** The low Furniture margin isn't widespread—it is heavily driven by **Tables** (-8.56% margin) and **Bookcases** (-3.02% margin), which together lost **-$21,198.04**.
* **Profit Cannibalization:** Strong profits from **Chairs** ($26.59K) and high-margin **Furnishings** (14.24%) are being eroded to compensate for net losses in Tables and Bookcases.

---

### Strategic Recommendations
1. **Discount Controls:** Re-evaluate promotional strategy and set strict discount caps on Tables and Bookcases.
2. **Cost Structure & Freight:** Audit shipping and freight costs for heavy goods (Tables/Bookcases) to ensure delivery costs aren't exceeding margin thresholds.
3. **Product Line Audit:** Re-assess vendor costs or prune unprofitable SKU items within the Tables sub-category.

In [9]:
query3 = """
SELECT
    p.sub_category AS "Sub-Category",
    SUM(i.sales) AS "Total Revenue",
    SUM(i.profit) AS "Total Profit",
    ROUND(
        (SUM(i.profit) / NULLIF(SUM(i.sales), 0)) * 100,
        2
    ) AS "Profit Margin %"
FROM superstore.order_items i
JOIN superstore.products p
    ON i.product_key = p.product_key
WHERE p.category = 'Furniture'
GROUP BY p.sub_category
ORDER BY SUM(i.profit) ASC;
"""
db_utils.run_pg_query(query3)

,Sub-Category,Total Revenue,Total Profit,Profit Margin %
0,Tables,206965.68,-17725.4811,-8.56
1,Bookcases,114880.05,-3472.5560,-3.02
2,Furnishings,91705.12,13059.1436,14.24
3,Chairs,328449.13,26590.1663,8.10


# BUSINESS CASE 4: CUSTOMER PROFITABILITY ANALYSIS

## Management Request

> "We know some customers are unprofitable. Which customers are generating losses, and which product categories are responsible for those losses?"

### Business Question

We want to determine:

1. Which customers are unprofitable overall?
2. How much revenue are these customers generating?
3. How much profit/loss are they generating?
4. Which categories are responsible for their losses?
5. Which customers represent the greatest financial risk?

### Analytical Approach

We will:

1. Calculate total profit for each customer.
2. Identify customers whose total profit is below zero.
3. Break those customers down by product category.
4. Identify categories where each unprofitable customer is losing money.
5. Quantify the losses from those unprofitable categories.
6. Prioritize customers based on the magnitude of their losses.

### Important Business Rule

A customer is considered **unprofitable** when:

`Total Customer Profit < 0`

A category is considered **unprofitable for a customer** when:

`Customer + Category Profit < 0`

QUERY 1 - UNPROFITABLE CUSTOMERS

In [15]:
query = """
WITH unprofitable_customers AS (
    SELECT
        o.customer_id
    FROM superstore.orders o
    JOIN superstore.order_items i
        ON o.order_id = i.order_id
    GROUP BY
        o.customer_id
    HAVING SUM(i.profit) < 0
)
SELECT *
FROM unprofitable_customers;
"""
db_utils.run_pg_query(query)


,customer_id
0,TS-21610
1,EM-13810
2,JR-15670
3,JH-16180
4,SB-20290
...,...
150,EH-14005
151,ZC-21910
152,SP-20620
153,MD-17350


Query 2 — Unprofitable customers by category

In [17]:
query = """
WITH unprofitable_customers AS (
    SELECT
        o.customer_id
    FROM superstore.orders o
    JOIN superstore.order_items i
        ON o.order_id = i.order_id
    GROUP BY
        o.customer_id
    HAVING SUM(i.profit) < 0
)

SELECT
    c.customer_name,
    p.category,
    SUM(i.sales) AS "Total Revenue",
    SUM(i.profit) AS "Total Profit",
    ROUND(
        (SUM(i.profit) / NULLIF(SUM(i.sales), 0)) * 100,
        2
    ) AS "Profit Margin %"
FROM superstore.customers c
JOIN superstore.orders o
    ON c.customer_id = o.customer_id
JOIN superstore.order_items i
    ON i.order_id = o.order_id
JOIN superstore.products p
    ON i.product_key = p.product_key
WHERE c.customer_id IN (
    SELECT customer_id
    FROM unprofitable_customers
)
GROUP BY
    c.customer_name,
    p.category
ORDER BY
    SUM(i.profit) ASC;
    """
db_utils.run_pg_query(query)

,customer_name,category,Total Revenue,Total Profit,Profit Margin %
0,Cindy Stewart,Technology,4955.97,-6397.9028,-129.09
1,Grant Thornton,Technology,7999.98,-3839.9904,-48.00
2,Luke Foster,Office Supplies,2945.39,-3611.9877,-122.63
3,Sharelle Roach,Technology,2549.99,-3399.9800,-133.33
4,Henry Goldwyn,Office Supplies,2993.09,-2854.2811,-95.36
...,...,...,...,...,...
420,Joseph Holt,Technology,1031.89,413.5968,40.08
421,Zuschuss Carroll,Furniture,3899.69,528.6897,13.56
422,Victoria Wilson,Office Supplies,1982.58,578.9763,29.20
423,Laurel Beltran,Office Supplies,3110.14,748.8433,24.08


Query 3 — Final customer-level loss analysis

In [12]:
query = """
WITH unprofitable_customers AS (
    SELECT
        o.customer_id
    FROM superstore.orders o
    JOIN superstore.order_items i
        ON o.order_id = i.order_id
    GROUP BY
        o.customer_id
    HAVING SUM(i.profit) < 0
),

customer_category_profit AS (
    SELECT
        o.customer_id,
        p.category,
        SUM(i.sales) AS category_revenue,
        SUM(i.profit) AS category_profit
    FROM superstore.orders o
    JOIN superstore.order_items i
        ON o.order_id = i.order_id
    JOIN superstore.products p
        ON i.product_key = p.product_key
    WHERE o.customer_id IN (
        SELECT customer_id
        FROM unprofitable_customers
    )
    GROUP BY
        o.customer_id,
        p.category
)

SELECT
    c.customer_name,
    SUM(ccp.category_revenue) AS "Total Revenue",
    SUM(ccp.category_profit) AS "Total Profit",

    SUM(
        CASE
            WHEN ccp.category_profit < 0
            THEN ccp.category_profit
            ELSE 0
        END
    ) AS "Loss From Unprofitable Categories",

    COUNT(
        CASE
            WHEN ccp.category_profit < 0
            THEN 1
        END
    ) AS "Unprofitable Categories"

FROM customer_category_profit ccp
JOIN superstore.customers c
    ON c.customer_id = ccp.customer_id

GROUP BY
    c.customer_id,
    c.customer_name

ORDER BY
    "Total Profit" ASC;
    """
db_utils.run_pg_query(query)

,customer_name,Total Revenue,Total Profit,Loss From Unprofitable Categories,Unprofitable Categories
0,Cindy Stewart,5690.07,-6626.3895,-6626.3895,2
1,Grant Thornton,9351.20,-4108.6589,-4187.1078,2
2,Luke Foster,3930.52,-3583.9770,-3638.9337,2
3,Sharelle Roach,3233.48,-3333.9144,-3399.9800,1
4,Henry Goldwyn,3247.65,-2797.9635,-2860.4691,2
...,...,...,...,...,...
150,Thais Sissman,4.84,-3.3156,-3.3156,1
151,Adrian Hane,1735.53,-2.3146,-296.5673,2
152,Mitch Gastineau,16.74,-1.2453,-3.0933,1
153,Paul Lucas,239.49,-0.7527,-13.6461,1


Query 4 — Rank the worst customers

In [13]:
query = """
WITH unprofitable_customers AS (
    SELECT
        o.customer_id
    FROM superstore.orders o
    JOIN superstore.order_items i
        ON o.order_id = i.order_id
    GROUP BY
        o.customer_id
    HAVING SUM(i.profit) < 0
),

customer_profit AS (
    SELECT
        o.customer_id,
        SUM(i.sales) AS total_revenue,
        SUM(i.profit) AS total_profit
    FROM superstore.orders o
    JOIN superstore.order_items i
        ON o.order_id = i.order_id
    WHERE o.customer_id IN (
        SELECT customer_id
        FROM unprofitable_customers
    )
    GROUP BY
        o.customer_id
)

SELECT
    c.customer_name,
    cp.total_revenue AS "Total Revenue",
    cp.total_profit AS "Total Profit",
    RANK() OVER (
        ORDER BY cp.total_profit ASC
    ) AS loss_rank
FROM customer_profit cp
JOIN superstore.customers c
    ON c.customer_id = cp.customer_id
ORDER BY
    loss_rank;
    """
db_utils.run_pg_query(query)

,customer_name,Total Revenue,Total Profit,loss_rank
0,Cindy Stewart,5690.07,-6626.3895,1
1,Grant Thornton,9351.20,-4108.6589,2
2,Luke Foster,3930.52,-3583.9770,3
3,Sharelle Roach,3233.48,-3333.9144,4
4,Henry Goldwyn,3247.65,-2797.9635,5
...,...,...,...,...
150,Thais Sissman,4.84,-3.3156,151
151,Adrian Hane,1735.53,-2.3146,152
152,Mitch Gastineau,16.74,-1.2453,153
153,Paul Lucas,239.49,-0.7527,154


Query 5 — Find the categories causing the biggest customer losses

In [14]:
query = """
WITH customer_category_profit AS (
    SELECT
        o.customer_id,
        p.category,
        SUM(i.sales) AS total_revenue,
        SUM(i.profit) AS total_profit
    FROM superstore.orders o
    JOIN superstore.order_items i
        ON o.order_id = i.order_id
    JOIN superstore.products p
        ON i.product_key = p.product_key
    GROUP BY
        o.customer_id,
        p.category
)

SELECT
    c.customer_name,
    ccp.category,
    ccp.total_revenue AS "Total Revenue",
    ccp.total_profit AS "Total Profit",
    ROUND(
        ccp.total_profit / NULLIF(ccp.total_revenue, 0) * 100,
        2
    ) AS "Profit Margin %"
FROM customer_category_profit ccp
JOIN superstore.customers c
    ON c.customer_id = ccp.customer_id
WHERE ccp.total_profit < 0
ORDER BY
    ccp.total_profit ASC;
    """
db_utils.run_pg_query(query)

,customer_name,category,Total Revenue,Total Profit,Profit Margin %
0,Cindy Stewart,Technology,4955.97,-6397.9028,-129.09
1,Grant Thornton,Technology,7999.98,-3839.9904,-48.00
2,Luke Foster,Office Supplies,2945.39,-3611.9877,-122.63
3,Sharelle Roach,Technology,2549.99,-3399.9800,-133.33
4,Henry Goldwyn,Office Supplies,2993.09,-2854.2811,-95.36
...,...,...,...,...,...
472,Larry Blacks,Furniture,1.99,-1.4413,-72.43
473,Maurice Satty,Technology,122.95,-1.1528,-0.94
474,Stephanie Phelps,Technology,1013.01,-1.1444,-0.11
475,Guy Thornton,Furniture,35.54,-0.8886,-2.50


Business Case 5 — Monthly Performance Trend

In [18]:
query = """
SELECT
    DATE_TRUNC('month', o.order_date) AS month,
    SUM(i.sales) AS "Total Revenue",
    SUM(i.profit) AS "Total Profit",
    ROUND(
        (SUM(i.profit) / NULLIF(SUM(i.sales), 0)) * 100,
        2
    ) AS "Profit Margin %"
FROM superstore.orders o
JOIN superstore.order_items i
    ON o.order_id = i.order_id
GROUP BY
    DATE_TRUNC('month', o.order_date)
ORDER BY
    month;
    """
db_utils.run_pg_query(query)

,month,Total Revenue,Total Profit,Profit Margin %
0,2014-01-01 00:00:00+00:00,14236.90,2450.1907,17.21
1,2014-02-01 00:00:00+00:00,4519.92,862.3084,19.08
2,2014-03-01 00:00:00+00:00,55691.04,498.7299,0.90
3,2014-04-01 00:00:00+00:00,28295.35,3488.8352,12.33
4,2014-05-01 00:00:00+00:00,23648.28,2738.7096,11.58
5,2014-06-01 00:00:00+00:00,34595.14,4976.5244,14.39
6,2014-07-01 00:00:00+00:00,33946.37,-841.4826,-2.48
7,2014-08-01 00:00:00+00:00,27909.47,5318.1050,19.05
8,2014-09-01 00:00:00+00:00,81777.34,8328.0994,10.18
9,2014-10-01 00:00:00+00:00,31453.37,3448.2573,10.96


# EXECUTIVE DASHBOARD DATASETS

In [19]:
# ============================================
# EXECUTIVE DASHBOARD
# ============================================

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# KPI DATASET

In [39]:
# ============================================
# KPI SUMMARY
# ============================================

kpi_query = """
SELECT
    SUM(sales) AS "Total Revenue",
    SUM(profit) AS "Total Profit",
    ROUND(
        (SUM(profit) / NULLIF(SUM(sales), 0)) * 100,
        2
    ) AS "Profit Margin %",
    COUNT(DISTINCT order_id) AS "Total Orders"
FROM superstore.order_items;
"""

kpi_df = db_utils.run_pg_query(kpi_query)

kpi_df

,Total Revenue,Total Profit,Profit Margin %,Total Orders
0,2297201.07,286397.0217,12.47,5009


## Orders By Category

In [40]:
orders_category_query = """
SELECT
    p.category AS "Category",
    COUNT(DISTINCT i.order_id) AS "Total Orders"
FROM superstore.order_items i
JOIN superstore.products p
    ON i.product_key = p.product_key
GROUP BY p.category
ORDER BY "Total Orders" DESC;
"""

orders_category_df = db_utils.run_pg_query(orders_category_query)

orders_category_df

,Category,Total Orders
0,Office Supplies,3742
1,Furniture,1764
2,Technology,1544


## Orders by region

In [41]:
orders_region_query = """
SELECT
    o.region AS "Region",
    COUNT(DISTINCT o.order_id) AS "Total Orders"
FROM superstore.orders o
GROUP BY o.region
ORDER BY "Total Orders" DESC;
"""

orders_region_df = db_utils.run_pg_query(orders_region_query)

orders_region_df

,Region,Total Orders
0,West,1611
1,East,1401
2,Central,1175
3,South,822


## Orders by state

In [42]:
orders_state_query = """
SELECT
    o.state AS "State",
    COUNT(DISTINCT o.order_id) AS "Total Orders"
FROM superstore.orders o
GROUP BY o.state
ORDER BY "Total Orders" DESC;
"""

orders_state_df = db_utils.run_pg_query(orders_state_query)

orders_state_df

,State,Total Orders
0,California,1021
1,New York,562
2,Texas,487
3,Pennsylvania,288
4,Illinois,276
5,Washington,256
6,Ohio,236
7,Florida,200
8,North Carolina,136
9,Michigan,117


## Orders By Customer

In [43]:
orders_customer_query = """
SELECT
    c.customer_name AS "Customer Name",
    COUNT(DISTINCT o.order_id) AS "Total Orders"
FROM superstore.orders o
JOIN superstore.customers c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY "Total Orders" DESC
LIMIT 10;
"""

orders_customer_df = db_utils.run_pg_query(orders_customer_query)

orders_customer_df

,Customer Name,Total Orders
0,Emily Phan,17
1,Chloris Kastensmidt,13
2,Joel Eaton,13
3,Noel Staavos,13
4,Sally Hughsby,13
5,Zuschuss Carroll,13
6,Patrick Gardner,13
7,Erin Ashbrook,13
8,Chris Selesnick,12
9,Bart Pistole,12


## CATEGORY PERFORMANCE

In [23]:
category_df = db_utils.run_pg_query("""
SELECT
    p.category,
    SUM(i.sales) AS revenue,
    SUM(i.profit) AS profit,
    ROUND(
        SUM(i.profit) / NULLIF(SUM(i.sales), 0) * 100,
        2
    ) AS profit_margin
FROM superstore.order_items i
JOIN superstore.products p
    ON i.product_key = p.product_key
GROUP BY
    p.category
ORDER BY
    profit DESC;
""")

category_df

,category,revenue,profit,profit_margin
0,Technology,836154.10,145454.9481,17.40
1,Office Supplies,719046.99,122490.8008,17.04
2,Furniture,741999.98,18451.2728,2.49


## Furniture sub-category performance

In [24]:
furniture_df = db_utils.run_pg_query("""
SELECT
    p.sub_category,
    SUM(i.sales) AS revenue,
    SUM(i.profit) AS profit,
    ROUND(
        SUM(i.profit) / NULLIF(SUM(i.sales), 0) * 100,
        2
    ) AS profit_margin
FROM superstore.order_items i
JOIN superstore.products p
    ON i.product_key = p.product_key
WHERE
    p.category = 'Furniture'
GROUP BY
    p.sub_category
ORDER BY
    profit ASC;
""")

furniture_df

,sub_category,revenue,profit,profit_margin
0,Tables,206965.68,-17725.4811,-8.56
1,Bookcases,114880.05,-3472.5560,-3.02
2,Furnishings,91705.12,13059.1436,14.24
3,Chairs,328449.13,26590.1663,8.10


## Monthly Performance

In [25]:
monthly_df = db_utils.run_pg_query("""
SELECT
    DATE_TRUNC('month', o.order_date) AS month,
    SUM(i.sales) AS revenue,
    SUM(i.profit) AS profit,
    ROUND(
        SUM(i.profit) / NULLIF(SUM(i.sales), 0) * 100,
        2
    ) AS profit_margin
FROM superstore.orders o
JOIN superstore.order_items i
    ON o.order_id = i.order_id
GROUP BY
    DATE_TRUNC('month', o.order_date)
ORDER BY
    month;
""")

monthly_df

,month,revenue,profit,profit_margin
0,2014-01-01 00:00:00+00:00,14236.90,2450.1907,17.21
1,2014-02-01 00:00:00+00:00,4519.92,862.3084,19.08
2,2014-03-01 00:00:00+00:00,55691.04,498.7299,0.90
3,2014-04-01 00:00:00+00:00,28295.35,3488.8352,12.33
4,2014-05-01 00:00:00+00:00,23648.28,2738.7096,11.58
5,2014-06-01 00:00:00+00:00,34595.14,4976.5244,14.39
6,2014-07-01 00:00:00+00:00,33946.37,-841.4826,-2.48
7,2014-08-01 00:00:00+00:00,27909.47,5318.1050,19.05
8,2014-09-01 00:00:00+00:00,81777.34,8328.0994,10.18
9,2014-10-01 00:00:00+00:00,31453.37,3448.2573,10.96


# Top 10 loss-making Customers

In [26]:
customer_loss_df = db_utils.run_pg_query("""
SELECT
    c.customer_name,
    SUM(i.sales) AS revenue,
    SUM(i.profit) AS profit,
    ROUND(
        SUM(i.profit) / NULLIF(SUM(i.sales), 0) * 100,
        2
    ) AS profit_margin
FROM superstore.customers c
JOIN superstore.orders o
    ON c.customer_id = o.customer_id
JOIN superstore.order_items i
    ON o.order_id = i.order_id
GROUP BY
    c.customer_id,
    c.customer_name
HAVING
    SUM(i.profit) < 0
ORDER BY
    profit ASC
LIMIT 10;
""")

customer_loss_df

,customer_name,revenue,profit,profit_margin
0,Cindy Stewart,5690.07,-6626.3895,-116.46
1,Grant Thornton,9351.20,-4108.6589,-43.94
2,Luke Foster,3930.52,-3583.9770,-91.18
3,Sharelle Roach,3233.48,-3333.9144,-103.11
4,Henry Goldwyn,3247.65,-2797.9635,-86.15
5,Nathan Cano,2218.99,-2204.8072,-99.36
6,Sean Braxton,8057.89,-2082.7451,-25.85
7,Sean Miller,25043.07,-1980.7393,-7.91
8,Christine Phan,5888.30,-1850.3029,-31.42
9,Natalie Fritzler,8322.82,-1695.9714,-20.38


# Loss by category

In [27]:
category_loss_df = db_utils.run_pg_query("""
SELECT
    p.category,
    SUM(i.profit) AS loss
FROM superstore.order_items i
JOIN superstore.products p
    ON i.product_key = p.product_key
GROUP BY
    p.category
HAVING
    SUM(i.profit) < 0
ORDER BY
    loss ASC;
""")

category_loss_df

,category,loss


## Top 10 customers by revenue

In [35]:
top_revenue_customers_df = db_utils.run_pg_query("""
SELECT
    c.customer_name,
    SUM(i.sales) AS revenue,
    SUM(i.profit) AS profit,
    ROUND(
        SUM(i.profit) / NULLIF(SUM(i.sales), 0) * 100,
        2
    ) AS profit_margin
FROM superstore.customers c
JOIN superstore.orders o
    ON c.customer_id = o.customer_id
JOIN superstore.order_items i
    ON o.order_id = i.order_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY
    revenue DESC
LIMIT 10;
""")

top_revenue_customers_df

,customer_name,revenue,profit,profit_margin
0,Sean Miller,25043.07,-1980.7393,-7.91
1,Tamara Chand,19052.22,8981.3239,47.14
2,Raymond Buch,15117.35,6976.0959,46.15
3,Tom Ashbrook,14595.62,4703.7883,32.23
4,Adrian Barton,14473.57,5444.8055,37.62
5,Ken Lonsdale,14175.23,806.8550,5.69
6,Sanjit Chand,14142.34,5757.4119,40.71
7,Hunter Lopez,12873.30,5622.4292,43.68
8,Sanjit Engle,12209.44,2650.6769,21.71
9,Christopher Conant,12129.08,2177.0493,17.95


## Top 10 customers by profit

In [36]:
top_profit_customers_df = db_utils.run_pg_query("""
SELECT
    c.customer_name,
    SUM(i.sales) AS revenue,
    SUM(i.profit) AS profit,
    ROUND(
        SUM(i.profit) / NULLIF(SUM(i.sales), 0) * 100,
        2
    ) AS profit_margin
FROM superstore.customers c
JOIN superstore.orders o
    ON c.customer_id = o.customer_id
JOIN superstore.order_items i
    ON o.order_id = i.order_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY
    profit DESC
LIMIT 10;
""")

top_profit_customers_df

,customer_name,revenue,profit,profit_margin
0,Tamara Chand,19052.22,8981.3239,47.14
1,Raymond Buch,15117.35,6976.0959,46.15
2,Sanjit Chand,14142.34,5757.4119,40.71
3,Hunter Lopez,12873.30,5622.4292,43.68
4,Adrian Barton,14473.57,5444.8055,37.62
5,Tom Ashbrook,14595.62,4703.7883,32.23
6,Christopher Martinez,8954.01,3899.8904,43.55
7,Keith Dawkins,8181.24,3038.6254,37.14
8,Andy Reiter,6608.45,2884.6208,43.65
9,Daniel Raglin,8350.87,2869.0760,34.36


## Regional performance

In [37]:
region_df = db_utils.run_pg_query("""
SELECT
    o.region,
    SUM(i.sales) AS revenue,
    SUM(i.profit) AS profit,
    ROUND(
        SUM(i.profit) / NULLIF(SUM(i.sales), 0) * 100,
        2
    ) AS profit_margin
FROM superstore.orders o
JOIN superstore.order_items i
    ON o.order_id = i.order_id
GROUP BY
    o.region
ORDER BY
    profit DESC;
""")

region_df

,region,revenue,profit,profit_margin
0,West,725457.93,108418.4489,14.94
1,East,678781.36,91522.7800,13.48
2,South,391721.90,46749.4303,11.93
3,Central,501239.88,39706.3625,7.92


## State Performance

In [38]:
state_df = db_utils.run_pg_query("""
SELECT
    o.state,
    SUM(i.sales) AS revenue,
    SUM(i.profit) AS profit,
    ROUND(
        SUM(i.profit) / NULLIF(SUM(i.sales), 0) * 100,
        2
    ) AS profit_margin
FROM superstore.orders o
JOIN superstore.order_items i
    ON o.order_id = i.order_id
GROUP BY
    o.state
ORDER BY
    profit DESC;
""")

state_df

,state,revenue,profit,profit_margin
0,California,457687.68,76381.3871,16.69
1,New York,310876.20,74038.5486,23.82
2,Washington,138641.29,33402.6517,24.09
3,Michigan,76269.61,24463.1876,32.07
4,Virginia,70636.72,18597.9504,26.33
5,Indiana,53555.36,18382.9363,34.33
6,Georgia,49095.84,16250.0433,33.10
7,Kentucky,36591.75,11199.6966,30.61
8,Minnesota,29863.15,10823.1874,36.24
9,Delaware,27451.07,9977.3748,36.35


In [28]:
print("KPI:", kpi_df.shape)
print("Category:", category_df.shape)
print("Furniture:", furniture_df.shape)
print("Monthly:", monthly_df.shape)
print("Customer Loss:", customer_loss_df.shape)
print("Category Loss:", category_loss_df.shape)

KPI: (1, 3)
Category: (3, 4)
Furniture: (4, 4)
Monthly: (48, 4)
Customer Loss: (10, 4)
Category Loss: (0, 2)


In [29]:
display(kpi_df)
display(category_df)
display(furniture_df)
display(customer_loss_df)

,total_revenue,total_profit,profit_margin
0,2297201.07,286397.0217,12.47


,category,revenue,profit,profit_margin
0,Technology,836154.10,145454.9481,17.40
1,Office Supplies,719046.99,122490.8008,17.04
2,Furniture,741999.98,18451.2728,2.49


,sub_category,revenue,profit,profit_margin
0,Tables,206965.68,-17725.4811,-8.56
1,Bookcases,114880.05,-3472.5560,-3.02
2,Furnishings,91705.12,13059.1436,14.24
3,Chairs,328449.13,26590.1663,8.10


,customer_name,revenue,profit,profit_margin
0,Cindy Stewart,5690.07,-6626.3895,-116.46
1,Grant Thornton,9351.20,-4108.6589,-43.94
2,Luke Foster,3930.52,-3583.9770,-91.18
3,Sharelle Roach,3233.48,-3333.9144,-103.11
4,Henry Goldwyn,3247.65,-2797.9635,-86.15
5,Nathan Cano,2218.99,-2204.8072,-99.36
6,Sean Braxton,8057.89,-2082.7451,-25.85
7,Sean Miller,25043.07,-1980.7393,-7.91
8,Christine Phan,5888.30,-1850.3029,-31.42
9,Natalie Fritzler,8322.82,-1695.9714,-20.38


# first executive visual: KPI cards.

In [30]:
fig = go.Figure()

fig.add_trace(go.Indicator(
    mode="number",
    value=kpi_df.loc[0, "total_revenue"],
    title={"text": "Total Revenue"},
    number={
        "prefix": "$",
        "valueformat": ",.2f"
    },
    domain={"row": 0, "column": 0}
))

fig.add_trace(go.Indicator(
    mode="number",
    value=kpi_df.loc[0, "total_profit"],
    title={"text": "Total Profit"},
    number={
        "prefix": "$",
        "valueformat": ",.2f"
    },
    domain={"row": 0, "column": 1}
))

fig.add_trace(go.Indicator(
    mode="number",
    value=kpi_df.loc[0, "profit_margin"],
    title={"text": "Profit Margin"},
    number={
        "suffix": "%",
        "valueformat": ".2f"
    },
    domain={"row": 0, "column": 2}
))

fig.update_layout(
    grid={
        "rows": 1,
        "columns": 3
    },
    height=250,
    margin=dict(l=20, r=20, t=60, b=20)
)

fig.show()

## Category profitability

In [31]:
fig = px.bar(
    category_df,
    x="category",
    y="profit",
    text="profit",
    title="Profit by Product Category"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    yaxis_title="Total Profit ($)",
    xaxis_title="Category"
)

fig.show()

# Furniture investigation

In [32]:
fig = px.bar(
    furniture_df,
    x="sub_category",
    y="profit",
    text="profit",
    title="Furniture Sub-Category Profitability"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.add_hline(
    y=0,
    line_width=1
)

fig.update_layout(
    yaxis_title="Total Profit ($)",
    xaxis_title="Furniture Sub-Category"
)

fig.show()

# Monthly Performance

In [33]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=monthly_df["month"],
    y=monthly_df["revenue"],
    mode="lines+markers",
    name="Revenue"
))

fig.add_trace(go.Scatter(
    x=monthly_df["month"],
    y=monthly_df["profit"],
    mode="lines+markers",
    name="Profit"
))

fig.update_layout(
    title="Monthly Revenue and Profit Trend",
    xaxis_title="Month",
    yaxis_title="Amount ($)",
    hovermode="x unified"
)

fig.show()

# Top Loss-Making Customers

In [34]:
fig = px.bar(
    customer_loss_df.sort_values("profit"),
    x="profit",
    y="customer_name",
    orientation="h",
    text="profit",
    title="Top 10 Loss-Making Customers"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.add_vline(
    x=0,
    line_width=1
)

fig.update_layout(
    xaxis_title="Total Profit ($)",
    yaxis_title="Customer"
)

fig.show()

In [44]:
kpi_df

,Total Revenue,Total Profit,Profit Margin %,Total Orders
0,2297201.07,286397.0217,12.47,5009


In [45]:
total_revenue = kpi_df["Total Revenue"].iloc[0]
total_profit = kpi_df["Total Profit"].iloc[0]
profit_margin = kpi_df["Profit Margin %"].iloc[0]
total_orders = kpi_df["Total Orders"].iloc[0]

In [46]:
print(total_revenue)
print(total_profit)
print(profit_margin)
print(total_orders)

2297201.07
286397.0217
12.47
5009


In [47]:
import plotly.graph_objects as go

In [48]:
fig = go.Figure()

fig.add_trace(go.Indicator(
    mode="number",
    value=total_revenue,
    title={"text": "Total Revenue"},
    number={"prefix": "$", "valueformat": ",.2f"},
    domain={"row": 0, "column": 0}
))

fig.add_trace(go.Indicator(
    mode="number",
    value=total_profit,
    title={"text": "Total Profit"},
    number={"prefix": "$", "valueformat": ",.2f"},
    domain={"row": 0, "column": 1}
))

fig.add_trace(go.Indicator(
    mode="number",
    value=profit_margin,
    title={"text": "Profit Margin"},
    number={"suffix": "%", "valueformat": ".2f"},
    domain={"row": 0, "column": 2}
))

fig.add_trace(go.Indicator(
    mode="number",
    value=total_orders,
    title={"text": "Total Orders"},
    number={"valueformat": ","},
    domain={"row": 0, "column": 3}
))

fig.update_layout(
    grid={"rows": 1, "columns": 4},
    height=180,
    margin={"l": 20, "r": 20, "t": 40, "b": 20}
)

fig.show()

In [49]:
category_df

,category,revenue,profit,profit_margin
0,Technology,836154.10,145454.9481,17.40
1,Office Supplies,719046.99,122490.8008,17.04
2,Furniture,741999.98,18451.2728,2.49


In [50]:
import plotly.express as px

fig = px.bar(
    category_df,
    x="category",
    y="profit",
    title="Profit by Category",
    text="profit"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    xaxis_title="Category",
    yaxis_title="Total Profit",
    template="plotly_white",
    height=450
)

fig.show()

In [51]:
fig = px.bar(
    furniture_df,
    x="sub_category",
    y="profit",
    title="Furniture Profit by Sub-Category",
    text="profit"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=450
)

fig.show()

In [52]:
fig = px.line(
    monthly_df,
    x="month",
    y=["revenue", "profit"],
    title="Monthly Revenue vs Profit",
    markers=True
)

fig.update_layout(
    template="plotly_white",
    height=450,
    xaxis_title="Month",
    yaxis_title="Amount ($)"
)

fig.show()

In [56]:
fig = px.bar(
    orders_category_df,
    x="Category",
    y="Total Orders",
    title="Orders by Category",
    text="Total Orders"
)

fig.update_traces(
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=400
)

fig.show()

In [62]:
fig = px.bar(
    region_df,
    x="region",
    y=["revenue", "profit"],
    barmode="group",
    title="Revenue vs Profit by Region"
)

fig.update_layout(
    template="plotly_white",
    height=400,
    yaxis_title="Amount ($)",
    xaxis_title="Region"
)

fig.show()

In [68]:
fig = px.bar(
    state_df.sort_values("profit"),
    x="profit",
    y="state",
    orientation="h",
    title="Profit Performance by State",
    text="profit"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=700,
    xaxis_title="Total Profit",
    yaxis_title="State"
)

fig.show()

In [70]:
fig = px.bar(
    top_revenue_customers_df.sort_values("revenue"),
    x="revenue",
    y="customer_name",
    orientation="h",
    title="Top 10 Customers by Revenue",
    text="revenue"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=500,
    xaxis_title="Revenue ($)",
    yaxis_title="Customer"
)

fig.show()

In [72]:
fig = px.bar(
    top_profit_customers_df.sort_values("profit"),
    x="profit",
    y="customer_name",
    orientation="h",
    title="Top 10 Customers by Profit",
    text="profit"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=500,
    xaxis_title="Profit ($)",
    yaxis_title="Customer"
)

fig.show()

In [74]:
fig = px.bar(
    customer_loss_df.sort_values("profit"),
    x="profit",
    y="customer_name",
    orientation="h",
    title="Top 10 Loss-Making Customers",
    text="profit"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=500,
    xaxis_title="Profit ($)",
    yaxis_title="Customer"
)

fig.show()

In [76]:
fig = px.bar(
    orders_region_df.sort_values("total_orders"),
    x="total_orders",
    y="region",
    orientation="h",
    title="Orders by Region",
    text="total_orders"
)

fig.update_traces(
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=400,
    xaxis_title="Total Orders",
    yaxis_title="Region"
)

fig.show()

In [78]:
fig = px.bar(
    orders_state_df.head(15).sort_values("total_orders"),
    x="total_orders",
    y="state",
    orientation="h",
    title="Top 15 States by Orders",
    text="total_orders"
)

fig.update_traces(
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=550,
    xaxis_title="Total Orders",
    yaxis_title="State"
)

fig.show()

In [80]:
fig = px.bar(
    orders_customer_df.sort_values("total_orders"),
    x="total_orders",
    y="customer_name",
    orientation="h",
    title="Top 10 Customers by Order Volume",
    text="total_orders"
)

fig.update_traces(
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=500,
    xaxis_title="Total Orders",
    yaxis_title="Customer"
)

fig.show()

In [81]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [82]:
total_revenue = kpi_df.loc[0, "Total Revenue"]
total_profit = kpi_df.loc[0, "Total Profit"]
profit_margin = kpi_df.loc[0, "Profit Margin %"]
total_orders = kpi_df.loc[0, "Total Orders"]

In [83]:
fig = go.Figure()

fig.add_trace(go.Indicator(
    mode="number",
    value=total_revenue,
    number={"prefix": "$", "valueformat": ",.0f"},
    title={"text": "Total Revenue"},
    domain={"x": [0, 0.25], "y": [0, 1]}
))

fig.add_trace(go.Indicator(
    mode="number",
    value=total_profit,
    number={"prefix": "$", "valueformat": ",.0f"},
    title={"text": "Total Profit"},
    domain={"x": [0.25, 0.5], "y": [0, 1]}
))

fig.add_trace(go.Indicator(
    mode="number",
    value=profit_margin,
    number={"suffix": "%", "valueformat": ".2f"},
    title={"text": "Profit Margin"},
    domain={"x": [0.5, 0.75], "y": [0, 1]}
))

fig.add_trace(go.Indicator(
    mode="number",
    value=total_orders,
    number={"valueformat": ",.0f"},
    title={"text": "Total Orders"},
    domain={"x": [0.75, 1], "y": [0, 1]}
))

fig.update_layout(
    template="plotly_white",
    height=180,
    margin=dict(l=20, r=20, t=40, b=20)
)

fig.show()

In [84]:
fig = px.bar(
    category_df.sort_values("profit"),
    x="profit",
    y="category",
    orientation="h",
    title="Profit by Category",
    text="profit"
)

fig.update_traces(
    texttemplate="$%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    height=400,
    xaxis_title="Profit ($)",
    yaxis_title="Category"
)

fig.show()

In [4]:
# ============================================================
# EXECUTIVE DASHBOARD
# ============================================================

from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.express as px


# ============================================================
# 1. CREATE DASHBOARD
# ============================================================

fig = make_subplots(
    rows=7,
    cols=2,

    # KPI row
    specs=[
        [
            {"type": "indicator"},
            {"type": "indicator"}
        ],
        [
            {"type": "indicator"},
            {"type": "indicator"}
        ],

        # Charts
        [{"type": "xy"}, {"type": "xy"}],
        [{"type": "xy"}, {"type": "xy"}],
        [{"type": "xy"}, {"type": "xy"}],
        [{"type": "xy"}, {"type": "xy"}],
        [{"type": "xy", "colspan": 2}, None],
    ],

    vertical_spacing=0.07,

    subplot_titles=(
        "",
        "",
        "",
        "",

        "Monthly Revenue vs Profit",
        "Profit by Category",

        "Orders by Category",
        "Furniture Profit by Sub-Category",

        "Top 10 Customers by Revenue",
        "Top 10 Customers by Profit",

        "Top 10 Loss-Making Customers",
        "",

        "State Profitability",
        ""
    )
)


# ============================================================
# 2. KPI CARDS
# ============================================================

fig.add_trace(
    go.Indicator(
        mode="number",
        value=kpi.loc[0, "Total Revenue"],
        title={"text": "TOTAL REVENUE"},
        number={
            "prefix": "$",
            "valueformat": ",.2f"
        }
    ),
    row=1,
    col=1
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=kpi.loc[0, "Total Profit"],
        title={"text": "TOTAL PROFIT"},
        number={
            "prefix": "$",
            "valueformat": ",.2f"
        }
    ),
    row=1,
    col=2
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=kpi.loc[0, "Profit Margin %"],
        title={"text": "PROFIT MARGIN"},
        number={
            "suffix": "%",
            "valueformat": ".2f"
        }
    ),
    row=2,
    col=1
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=kpi.loc[0, "Total Orders"],
        title={"text": "TOTAL ORDERS"},
        number={
            "valueformat": ","
        }
    ),
    row=2,
    col=2
)


# ============================================================
# 3. MONTHLY REVENUE VS PROFIT
# ============================================================

fig.add_trace(
    go.Scatter(
        x=monthly_df["Month"],
        y=monthly_df["Revenue"],
        mode="lines+markers",
        name="Revenue"
    ),
    row=3,
    col=1
)

fig.add_trace(
    go.Scatter(
        x=monthly_df["Month"],
        y=monthly_df["Profit"],
        mode="lines+markers",
        name="Profit"
    ),
    row=3,
    col=1
)


# ============================================================
# 4. PROFIT BY CATEGORY
# ============================================================

fig.add_trace(
    go.Bar(
        x=category_df["category"],
        y=category_df["profit"],
        text=category_df["profit"],
        texttemplate="$%{text:,.0f}",
        textposition="outside",
        name="Profit"
    ),
    row=3,
    col=2
)


# ============================================================
# 5. ORDERS BY CATEGORY
# ============================================================

fig.add_trace(
    go.Bar(
        x=orders_category_df["Category"],
        y=orders_category_df["Total Orders"],
        text=orders_category_df["Total Orders"],
        textposition="outside",
        name="Orders"
    ),
    row=4,
    col=1
)


# ============================================================
# 6. FURNITURE
# ============================================================

fig.add_trace(
    go.Bar(
        x=furniture_df["Sub-Category"],
        y=furniture_df["Total Profit"],
        text=furniture_df["Total Profit"],
        texttemplate="$%{text:,.0f}",
        textposition="outside",
        name="Furniture Profit"
    ),
    row=4,
    col=2
)


# ============================================================
# 7. TOP REVENUE CUSTOMERS
# ============================================================

fig.add_trace(
    go.Bar(
        x=top_revenue_customers_df["revenue"],
        y=top_revenue_customers_df["customer_name"],
        orientation="h",
        text=top_revenue_customers_df["revenue"],
        texttemplate="$%{text:,.0f}",
        textposition="outside",
        name="Revenue"
    ),
    row=5,
    col=1
)


# ============================================================
# 8. TOP PROFIT CUSTOMERS
# ============================================================

fig.add_trace(
    go.Bar(
        x=top_profit_customers_df["profit"],
        y=top_profit_customers_df["customer_name"],
        orientation="h",
        text=top_profit_customers_df["profit"],
        texttemplate="$%{text:,.0f}",
        textposition="outside",
        name="Profit"
    ),
    row=5,
    col=2
)


# ============================================================
# 9. LOSS-MAKING CUSTOMERS
# ============================================================

fig.add_trace(
    go.Bar(
        x=customer_loss_df["Total Profit"],
        y=customer_loss_df["Customer Name"],
        orientation="h",
        text=customer_loss_df["Total Profit"],
        texttemplate="$%{text:,.0f}",
        textposition="outside",
        name="Loss"
    ),
    row=6,
    col=1
)


# ============================================================
# 10. STATE PERFORMANCE
# ============================================================

state_sorted = state_df.sort_values(
    "profit",
    ascending=True
)

fig.add_trace(
    go.Bar(
        x=state_sorted["profit"],
        y=state_sorted["state"],
        orientation="h",
        text=state_sorted["profit"],
        texttemplate="$%{text:,.0f}",
        textposition="outside",
        name="State Profit"
    ),
    row=7,
    col=1
)


# ============================================================
# 11. TITLES / AXES
# ============================================================

fig.update_xaxes(
    title_text="Month",
    row=3,
    col=1
)

fig.update_yaxes(
    title_text="Amount ($)",
    row=3,
    col=1
)

fig.update_xaxes(
    title_text="Profit ($)",
    row=3,
    col=2
)

fig.update_yaxes(
    title_text="Profit ($)",
    row=4,
    col=2
)

fig.update_xaxes(
    title_text="Revenue ($)",
    row=5,
    col=1
)

fig.update_xaxes(
    title_text="Profit ($)",
    row=5,
    col=2
)

fig.update_xaxes(
    title_text="Profit ($)",
    row=6,
    col=1
)

fig.update_xaxes(
    title_text="Profit ($)",
    row=7,
    col=1
)


# ============================================================
# 12. SORT HORIZONTAL BAR CHARTS
# ============================================================

fig.update_yaxes(
    categoryorder="total ascending",
    row=5,
    col=1
)

fig.update_yaxes(
    categoryorder="total ascending",
    row=5,
    col=2
)

fig.update_yaxes(
    categoryorder="total descending",
    row=6,
    col=1
)


# ============================================================
# 13. DASHBOARD TITLE
# ============================================================

fig.update_layout(
    title={
        "text": "SUPERSTORE EXECUTIVE BUSINESS PERFORMANCE DASHBOARD",
        "x": 0.5,
        "xanchor": "center",
        "font": {
            "size": 24
        }
    },

    template="plotly_white",

    height=2800,

    showlegend=False,

    margin=dict(
        l=80,
        r=80,
        t=100,
        b=80
    )
)


# ============================================================
# 14. DISPLAY
# ============================================================

fig.show()

NameError: name 'kpi' is not defined